const translations = {
    "uk": {
        "desc_nesty": "Легковажна утиліта для Windows, яка вводить систему «сіток» (Fences) для групування ярликів.",
        "desc_aether": "Десктопний AI-асистент, що працює як напівпрозорий overlay поверх усіх вікон із захопленням аудіо та розпізнаванням екрана.",
        "desc_deckboard": "Екосистема з Android-застосунку і Python-сервера на ПК, які утворюють повноцінну «стрім-панель».",
        "desc_androidcalc": "Мобільний застосунок-калькулятор для Android, розроблений на замовлення Харківського водоканалу.",
        "desc_homecinema": "Локальний медіасервер, що поєднує телевізори на Android TV з мережевим сховищем (NAS).",
        "problem_title": "Проблема",
        "solution_title": "Рішення",
        "nesty_subtitle_full": "Легковажна утиліта для Windows, яка вводить систему «сіток» (Fences) для групування ярликів.",
        "nesty_problem": "Стандартний робочий стіл Windows швидко перетворюється на хаотичне нагромадження ярликів і файлів, а вбудовані інструменти системи не дають гнучких способів організувати простір під себе.",
        "nesty_solution": "Nestly — легковажна утиліта для Windows, яка вводить систему «сіток» (Fences) для групування ярликів. Вікна сіток автоматично згортаються в тонку панель, коли курсор залишає їхні межі, і розгортаються при наведенні, звільняючи візуальний простір. Магнітне прилипання сіток одна до одної та до країв екрана (з точністю до 20 пікселів) дозволяє вибудувати ідеально впорядкований робочий стіл без ручного вирівнювання.",
        "nesty_feat_title": "Ключові особливості",
        "nesty_feat_1": "Автоматичне згортання та розгортання сіток при наведенні курсора",
        "nesty_feat_2": "Магнітне прилипання (snapping) з точністю 20 px",
        "nesty_feat_3": "5 вбудованих неонових пресетів оформлення + власний пресет за HEX-кодом",
        "nesty_feat_4": "Безпечне переміщення файлів назад на робочий стіл при видаленні сітки",
        "nesty_feat_5": "Інтеграція з контекстним меню Windows та автозапуск разом із системою",
        "nesty_feat_6": "Підтримка Drag & Drop",
        "nesty_feat_7": "Повноцінний інсталятор для встановлення в кілька кліків",
        "aether_subtitle": "Десктопний AI-асистент, що працює як напівпрозорий overlay поверх усіх вікон із захопленням аудіо та розпізнаванням екрана.",
        "aether_problem": "Під час навчання чи роботи студентам і фахівцям часто бракує швидкого способу отримати стислу підказку на основі того, що вони чують або бачать на екрані, — без перемикання між вікнами й відволікання від основного процесу.",
        "aether_solution": "Aether — десктопний AI-асистент, що працює як напівпрозорий overlay поверх усіх вікон. Програма захоплює аудіо з мікрофона та транскрибує його через Groq Whisper, а також розпізнає текст на екрані за допомогою Gemini Vision (OCR). Отримані дані передаються у Groq LLM, який генерує стислу й точну відповідь просто на екрані користувача. Окрема функція робить overlay невидимим під час демонстрації екрана, що дозволяє використовувати асистента непомітно.",
        "aether_feat_title": "Ключові особливості",
        "aether_feat_1": "Захоплення та транскрипція аудіо в реальному часі",
        "aether_feat_2": "OCR вибраної області екрана",
        "aether_feat_3": "Генерація відповідей через LLM на основі аудіо та візуальних даних",
        "aether_feat_4": "Режим невидимості під час демонстрації екрана",
        "aether_feat_5": "Повний набір гарячих клавіш для керування без відриву від основного завдання",
        "aether_feat_6": "Налаштування власних API-ключів (Groq, Gemini) безпосередньо в програмі",
        "deckboard_subtitle": "Екосистема з Android-застосунку і Python-сервера на ПК, які утворюють повноцінну «стрім-панель» дистанційного керування.",
        "deckboard_problem": "Керування комп'ютером під час стрімів, презентацій чи звичайної роботи часто вимагає постійного перемикання між клавіатурою і мишею для простих дій — вимкнення мікрофона, запуску запису в OBS чи відкриття потрібної програми.",
        "deckboard_solution": "DeckBoard — екосистема з двох частин: Android-застосунок і Python-сервер на ПК, які утворюють повноцінну «стрім-панель» дистанційного керування. Через мобільний застосунок користувач одним дотиком керує звуком, записом в OBS та запуском будь-яких програм на комп'ютері, а сервер автоматично виявляється в локальній мережі, що робить підключення практично миттєвим.",
        "deckboard_feat_title": "Ключові особливості",
        "deckboard_feat_1": "Кастомізовані плитки керування з підтримкою Drag & Drop",
        "deckboard_feat_2": "Автоматичний пошук сервера в локальній мережі або ручне підключення за IP",
        "deckboard_feat_3": "Керування системним звуком і мікрофоном одним дотиком",
        "deckboard_feat_4": "Дистанційний старт/стоп запису через інтеграцію з OBS WebSocket",
        "deckboard_feat_5": "Запуск довільних програм і ярликів (.exe, .lnk, .url) із системного трея",
        "deckboard_feat_6": "Модульна структура репозиторію (окремо Android-клієнт і PC-сервер)",
        "androidcalc_subtitle": "Завершений мобільний застосунок-калькулятор для Android, розроблений на замовлення Харківського водоканалу.",
        "androidcalc_problem": "Замовнику — Харківському водоканалу — потрібен був надійний, готовий до інтеграції мобільний калькулятор із сучасним інтерфейсом для внутрішнього використання.",
        "androidcalc_solution": "AndroidCalc — завершений мобільний застосунок-калькулятор для Android, розроблений на замовлення Харківського водоканалу. Проєкт реалізує повний набір базових математичних операцій у чистому, добре задокументованому коді, готовому до подальшого розширення функціоналу та інтеграції в більші системи замовника.",
        "androidcalc_feat_title": "Ключові особливості",
        "androidcalc_feat_1": "Розроблено на замовлення Харківського водоканалу",
        "androidcalc_feat_2": "Сучасний і чуйний UI/UX дизайн",
        "androidcalc_feat_3": "Повна підтримка базових математичних операцій",
        "androidcalc_feat_4": "Адаптивність під різні роздільні здатності екрана",
        "androidcalc_feat_5": "Чистий, документований код, готовий до розширення та інтеграції",
        "homecinema_subtitle": "Локальний медіасервер, що поєднує телевізори на Android TV з мережевим сховищем (NAS) у домашній мережі.",
        "homecinema_problem": "Комерційні стрімінгові сервіси залежать від інтернет-з'єднання, підписок і зовнішніх серверів, тоді як багато користувачів мають власну медіатеку та хочуть переглядати її на телевізорі без затримок і сторонніх обмежень.",
        "homecinema_solution": "HomeCinema — локальний медіасервер, що поєднує телевізори на Android TV з мережевим сховищем (NAS) у домашній мережі. Проєкт відтворює звичний досвід популярних стрімінгових платформ — зручний каталог, обкладинки, описи — але повністю локально, без затримок і залежності від зовнішніх серверів. Веб-адмінка дозволяє легко поповнювати бібліотеку, а метадані фільмів підтягуються автоматично.",
        "homecinema_feat_title": "Ключові особливості",
        "homecinema_feat_1": "Веб-адмінпанель для завантаження та керування бібліотекою фільмів",
        "homecinema_feat_2": "Автоматичне підтягування обкладинок, описів і метаданих",
        "homecinema_feat_3": "Інтерфейс для Android TV, адаптований під керування пультом",
        "homecinema_feat_4": "Повністю локальна робота без затримок і залежності від хмарних сервісів",

        "nav_home": "Головна",
        "nav_spec": "Спеціалізація",
        "nav_services": "Послуги",
        "nav_process": "Процес",
        "nav_about": "Про мене",
        "nav_projects": "Проєкти",
        "nav_status": "Статус",
        "services_title_1": "Мої",
        "services_title_2": "Послуги",
        "services_subtitle": "Що саме я можу зробити для вас",
        "srv_desktop_title": "Розробка десктоп-застосунків",
        "srv_desktop_desc": "Створюю кастомні утиліти та інструменти під Windows — від автоматизації рутинних задач до застосунків з власним інтерфейсом.",
        "srv_desktop_f1": "Кастомний UI (PyQt6, Electron, WPF/C#)",
        "srv_desktop_f2": "Автоматизація задач і системні скрипти",
        "srv_desktop_f3": "Інтеграція з Windows API і реєстром",
        "srv_desktop_f4": "Готові до дистрибуції (.exe, інсталятори)",
        "srv_bots_title": "Telegram-боти з інтеграцією AI",
        "srv_bots_desc": "Пишу ботів, які вміють більше за стандартні команди — від простої автоматизації до повноцінних AI-асистентів.",
        "srv_bots_f1": "Розпізнавання голосу (Whisper / Groq)",
        "srv_bots_f2": "Інтеграція з LLM (GPT, Groq, Gemini)",
        "srv_bots_f3": "Обробка природної мови та NLP-сценарії",
        "srv_bots_f4": "Бізнес-воронки та автовідповіді",
        "srv_android_title": "Android-застосунки",
        "srv_android_desc": "Розробка мобільних застосунків під Android — від простих утиліт до застосунків з інтеграцією зовнішніх сервісів.",
        "srv_android_f1": "Нативна розробка (Kotlin / Java)",
        "srv_android_f2": "Інтеграція із зовнішніми API та сервісами",
        "srv_android_f3": "Адаптивний UI/UX під різні екрани",
        "srv_android_f4": "Готово до публікації в Play Store",
        "srv_auto_title": "Автоматизація процесів",
        "srv_auto_desc": "Парсери, скрипти обробки даних, інтеграції між сервісами — рутинні задачі виконуються без ручного втручання.",
        "srv_auto_f1": "Веб-скрапінг та парсери (BeautifulSoup, Selenium)",
        "srv_auto_f2": "Обробка та трансформація даних (Excel, JSON, CSV)",
        "srv_auto_f3": "Інтеграції між API та сервісами",
        "srv_auto_f4": "Scheduled-задачі та фонові процеси",
        "srv_consult_title": "Консультації та доопрацювання",
        "srv_consult_desc": "Допомагаю довести проєкт до ладу — незалежно від стадії: від аудиту коду до архітектурних рекомендацій.",
        "srv_consult_f1": "Code review та аудит кодової бази",
        "srv_consult_f2": "Виправлення багів і рефакторинг",
        "srv_consult_f3": "Архітектурні рекомендації",
        "srv_consult_f4": "Допомога з доробкою MVP до продакшну",
        "hero_badge": "Відкритий до проєктів та пропозицій",
        "hero_title_1": "Створюю",
        "hero_title_2": "надійні",
        "hero_title_3": "програмні рішення",
        "hero_subtitle": "Архітектура, розробка та автоматизація. Від утиліт для ОС до розумних мобільних додатків та AI-інтеграцій.",
        "btn_contact_tg": "Написати в Telegram",
        "btn_watch_projects": "Дивитись проєкти",
        "spec_title_1": "Моя",
        "spec_title_2": "Спеціалізація",
        "spec_subtitle": "Ключові напрямки, в яких я приношу максимальну користь",
        "spec_desktop": "Desktop Tools",
        "spec_desktop_desc": "Розробка нативних та кросплатформних утиліт (Python/PyQt6, Electron).",
        "spec_mobile": "Mobile Apps",
        "spec_mobile_desc": "Нативна розробка під Android (Kotlin, Java) та інтеграція з залізом.",
        "spec_ai": "AI Integration",
        "spec_ai_desc": "Впровадження LLM моделей, парсинг даних та створення розумних асистентів.",
        "spec_auto": "Automation",
        "spec_auto_desc": "Скрипти, боти та веб-парсери для автоматизації рутинних бізнес-задач.",
        "proj_title_1": "Мої",
        "proj_title_2": "Творіння",
        "proj_subtitle": "Вибрані проєкти з детальним описом архітектури",
        "filter_all": "Всі",
        "filter_desktop": "Desktop",
        "filter_mobile": "Mobile",
        "filter_ai": "AI / LLM",
        "btn_details": "Детальніше",
        "status_dev": "В розробці",
        "desc_nesty": "Стильна утиліта для Windows. Дозволяє створювати 'сітки' для групування ярликів на робочому столі.",
        "desc_aether": "Десктопний AI-асистент із захопленням аудіо (Groq Whisper) та розпізнаванням екрану поверх усіх вікон.",
        "desc_aitrainer": "Інструмент для глибокого навчання. Аналізує матеріал через AI та генерує персональні тести.",
        "desc_deckboard": "Екосистема для управління ПК зі смартфона. Перемикання сцен OBS, макроси та автозапуск.",
        "desc_homecinema": "Власний локальний медіасервер. Зручна веб-адмінка та клієнт під Android TV.",
        "workflow_title_1": "Процес",
        "workflow_title_2": "Роботи",
        "workflow_subtitle": "Прозорий та зрозумілий підхід до розробки продуктів",
        "step1_title": "Обговорення",
        "step1_desc": "Аналіз завдання, підбір оптимального стеку технологій та складання ТЗ.",
        "step2_title": "MVP / Прототип",
        "step2_desc": "Швидке створення базової версії для тестування гіпотез та механік.",
        "step3_title": "Доробка",
        "step3_desc": "Інтеграція дизайну, додавання фіч, відлов багів та оптимізація коду.",
        "step4_title": "Підтримка",
        "step4_desc": "Передача готового коду, написання інструкцій та консультації по деплою.",
        "about_title_1": "Про",
        "about_title_2": "Мене",
        "about_role": "Владислав / Розробник",
        "about_bio": "Я спеціалізуюсь на створенні зручних, швидких та естетичних програмних рішень. Моя мета — не просто писати код, а розробляти інструменти, які дійсно вирішують проблеми користувачів, будь то кастомізація робочого столу, навчання за допомогою AI чи автоматизація бізнес-процесів.",
        "about_placeholder": "Заглушка фото (me.jpg)",
        "about_test1": "\"Слот для майбутнього відгуку замовника. Відмінний проєкт, зроблено вчасно!\"",
        "about_test2": "\"Кейс-стаді або ще один відгук, що підвищує довіру.\"",
        "status_title_1": "Зараз в",
        "status_title_2": "Роботі",
        "status_subtitle": "Лог активності та актуальний статус проєктів",
        "time1_date": "2026-06-13",
        "time1_title": "> [DEV] HomeCinema",
        "time1_desc": "Пишу веб-адмінку для локального медіасервера. Завершена логіка автозаповнення метаданих.",
        "time2_date": "2026-05-20",
        "time2_title": "> [TEST] Aether",
        "time2_desc": "Інтеграція LLM та OCR в десктопний асистент. Розпізнавання екрану успішно проходить QA.",
        "time3_date": "2026-04-15",
        "time3_title": "> [RELEASE] DeckBoard 1.0",
        "time3_desc": "Зв'язка Kotlin + Python відправлена в реліз. Стабільна робота на Windows та Android.",
        "cta_title": "Чи готові обговорити завдання?",
        "cta_desc": "Розкажіть про вашу ідею, і ми знайдемо найкраще технічне рішення для її реалізації.",
        "cta_email": "Відправити Email",
        "footer_rights": "&copy; 2026 Владислав.",
        "back_to_portfolio": "← Назад у Портфоліо",
        "nesty_subtitle_full": "Стильна та легковагова утиліта для Windows, створена для ідеального порядку на робочому столі.",
        "label_platform": "Платформа:",
        "label_tech": "Технології:",
        "nesty_feat_title": " Головні фішки",
        "nesty_feat_1": "<strong> Розумне згортання:</strong> Вікна автоматично згортаються в тонку шапку, коли миша залишає їх межі, і плавно розгортаються при наведенні.",
        "nesty_feat_2": "<strong> Магнітне прилипання (Snapping):</strong> Сітки акуратно магнітяться одна до одної та до країв екрану (дистанція 20 пікселів) для створення ідеального піксельного порядку.",
        "nesty_feat_3": "<strong> Глибока кастомізація:</strong> 5 вбудованих неонових пресетів (Синій, Фіолетовий, Зелений, Помаранчевий, Червоний) + можливість створити свій пресет за HEX-кодом через палітру.",
        "nesty_feat_4": "<strong> Безпека файлів:</strong> При видаленні сітки всі файли з неї автоматично і безпечно переміщуються назад на Робочий стіл.",
        "nesty_feat_5": "<strong> Інтеграція з Windows:</strong> Програма додає пункт \"Створити Сітку (Fences)\" прямо в контекстне меню робочого столу і автоматично запускається разом із системою.",
        "nesty_feat_6": "<strong> Drag & Drop:</strong> Файли легко перетягуються всередину сітки звичайним рухом миші.",
        "nesty_install_title": " Встановлення",
        "nesty_install_desc": "Оскільки програма запакована в повноцінний інсталятор, встановлення займає всього пару кліків:",
        "nesty_install_1": "Запустіть файл <code>Nestly_Setup.exe</code>.",
        "nesty_install_2": "Дотримуйтесь інструкцій на екрані. Інсталятор автоматично додасть програму в Автозавантаження і пропише контекстне меню.",
        "nesty_install_3": "Готово! Програма вже працює у фоновому режимі.",
        "nesty_dev_title": " Для розробників (Збірка з вихідних кодів)",
        "btn_github": "Подивитися на GitHub",
        "screen_1": "Скрін 1",
        "screen_2": "Скрін 2",
        "screen_3": "Скрін 3",
        "screen_4": "Скрін 4",
        "video": "Відео",
        "btn_repo_closed": "Репозиторій поки закрито",
        "aether_subtitle": "Десктопний AI-асистент для студентів — напівпрозорий overlay поверх усіх вікон із захопленням аудіо та екрану.",
        "aether_feat_title": " Можливості",
        "aether_feat_1": "<strong> Захоплення аудіо:</strong> запис з мікрофона + транскрипція через Whisper (Groq API).",
        "aether_feat_2": "<strong> OCR екрану:</strong> скріншот вибраної області + розпізнавання тексту через Gemini Vision.",
        "aether_feat_3": "<strong> LLM відповіді:</strong> швидка генерація стислих, точних відповідей через Groq LLM.",
        "aether_feat_4": "<strong> Невидимість:</strong> overlay повністю невидимий під час демонстрації екрану (Windows 10/11).",
        "aether_feat_5": "<strong> Гарячі клавіші:</strong> управління без відриву від основного процесу.",
        "aether_install_title": " Встановлення",
        "aether_hotkeys_title": " Гарячі клавіші",
        "aether_hk_col1": "Комбінація",
        "aether_hk_col2": "Дія",
        "aether_hk_1": "Сховати/показати overlay",
        "aether_hk_2": "Увімкнути/вимкнути запис аудіо",
        "aether_hk_3": "Зробити скріншот області",
        "aether_hk_4": "Перемкнути невидимість для демонстрації екрана",
        "aether_hk_5": "Вихід із програми",
        "aether_api_title": " API Ключі",
        "aether_api_desc": "Для роботи необхідні безкоштовні API-ключі:",
        "aether_api_1": "<strong>Groq API</strong> — console.groq.com (STT + LLM, безкоштовно)",
        "aether_api_2": "<strong>Google Gemini API</strong> — aistudio.google.com (OCR, безкоштовно)",
        "aether_api_footer": "Ключі вводяться в налаштуваннях програми (іконка ).",
        "ai_trainer_subtitle": "Потужний інструмент для глибокого та продуктивного вивчення будь-якої інформації з використанням AI.",
        "ai_trainer_concept_title": "Ідея та принцип роботи",
        "ai_trainer_concept_p1": "AI Trainer спочатку розроблявся студентами для студентів з метою спростити глибоке вивчення складної інформації. Однак принцип його роботи робить можливим його використання в будь-якій сфері для абсолютно будь-якої людини незалежно від рівня її знань.",
        "ai_trainer_concept_p2": "В основі складання всіх тестів лежить ШІ, який аналізує заданий Вами матеріал, і на його основі складає певну кількість питань з різними форматами відповідей. Усі виконувані моделі, які доступні Вам у програмі, є частиною безкоштовної некомерційної бібліотеки <code>g4f</code>, що дозволяє використовувати масу закритих моделей без обмежень.",
        "ai_trainer_tech_title": "Технічні деталі",
        "ai_trainer_tech_p1": "За допомогою асинхронної оболонки класу <code>AIClient</code> Ви можете звертатися відразу до декількох моделей одночасно, або ж у різних чатах, при цьому не блокуючи основний потік виконання.",
        "ai_trainer_tech_p2": "<strong>Важлива примітка:</strong> Просимо не підвищувати значення лімітів, таких як <code>ThreadPoolExecutor(max_workers=4)</code> або <code>max_tokens=1200</code>, щоб надмірно не перевантажувати сервери провайдерів.",
        "ai_trainer_lang_title": "Локалізація",
        "deckboard_subtitle": "Потужна екосистема для дистанційного керування вашим комп'ютером прямо зі смартфона.",
        "deckboard_feat_title": " Основні можливості",
        "deckboard_android_title": " Android Додаток (Client)",
        "deckboard_android_1": "<strong>Кастомізація:</strong> Повна свобода дій з підтримкою Drag-and-Drop для сортування плиток.",
        "deckboard_android_2": "<strong>Інтуїтивність:</strong> Сучасний інтерфейс з плавною анімацією та зворотним зв'язком.",
        "deckboard_android_3": "<strong>Розумне підключення:</strong> Автоматичний пошук сервера в локальній мережі або ручне введення IP зі збереженням.",
        "deckboard_pc_title": " PC Сервер (Python)",
        "deckboard_pc_1": "<strong>Керування звуком:</strong> Швидке перемикання мута мікрофона та системного звуку (Speakers).",
        "deckboard_pc_2": "<strong>Інтеграція з OBS:</strong> Дистанційний запуск і зупинка запису через WebSocket.",
        "deckboard_pc_3": "<strong>Запуск софту:</strong> Можливість додавати будь-які ярлики (.exe, .lnk, .url) прямо з системного трея.",
        "deckboard_pc_4": "<strong>Зручність:</strong> Поточна IP-адреса сервера завжди видна в меню трея для швидкого налаштування.",
        "deckboard_structure_title": " Структура проєкту",
        "deckboard_structure_desc": "Репозиторій розділений на дві логічні частини:",
        "deckboard_structure_1": "<code>/AndroidApp</code> — Вихідний код мобільного додатка (Kotlin/Android Studio).",
        "deckboard_structure_2": "<code>/pc-server</code> — Серверна частина на Python з використанням Flask і PyStray.",
        "deckboard_stack_title": " Технологічний стек",
        "deckboard_stack_1": "<strong>Android:</strong> Kotlin, Retrofit2, SharedPreferences, ItemTouchHelper.",
        "deckboard_stack_2": "<strong>Backend:</strong> Python, Flask, OBS-WebSocket, PyCaw, PyStray, NirCmd.",
        "homecinema_badge": "В активній розробці",
        "homecinema_subtitle": "Власний локальний домашній кінотеатр, що зв'язує Android TV з мережевим сховищем.",
        "homecinema_concept_title": "Концепція",
        "homecinema_concept_p1": "HomeCinema — це проєкт, який пов'язує телевізори на базі Android з локальним сховищем (NAS) у домашній мережі, дозволяючи з комфортом дивитися фільми та серіали.",
        "homecinema_concept_p2": "Оформлення та користувацький досвід (UX) натхненні популярними стрімінговими сервісами, але працюють повністю локально і без затримок.",
        "homecinema_feat_title": "Ключові фічі (Поточний білд)",
        "homecinema_feat_1": "<strong>Власна Адмін-панель:</strong> Зручний веб-інтерфейс, через який легко завантажувати нові фільми в бібліотеку.",
        "homecinema_feat_2": "<strong>Розумне автозаповнення:</strong> Під час додавання фільму обкладинки, описи та метадані підтягуються автоматично.",
        "homecinema_feat_3": "<strong>Плавний UI для Android TV:</strong> Інтерфейс адаптований спеціально для керування з пульта дистанційного керування телевізора.",
        "homecinema_note": "Проєкт на даний момент не опубліковано на GitHub, оскільки він перебуває в стадії активної розробки, але вже має повністю робочий білд."
    },
    "en": {
        "desc_nesty": "Lightweight Windows utility that introduces a 'fences' system to group desktop shortcuts.",
        "desc_aether": "Desktop AI assistant working as a semi-transparent overlay on all windows with audio capture and screen recognition.",
        "desc_deckboard": "Ecosystem consisting of an Android app and a Python PC server forming a complete 'stream-deck'.",
        "desc_androidcalc": "Mobile calculator app for Android, developed for the Kharkiv Water Utility company.",
        "desc_homecinema": "Local media server connecting Android TVs with Network Attached Storage (NAS).",
        "problem_title": "Problem",
        "solution_title": "Solution",
        "nesty_subtitle_full": "Lightweight Windows utility that introduces a 'fences' system to group desktop shortcuts.",
        "nesty_problem": "The standard Windows desktop quickly turns into a chaotic pile of shortcuts and files, and built-in system tools do not provide flexible ways to organize the space to your liking.",
        "nesty_solution": "Nestly is a lightweight Windows utility that introduces a system of 'fences' for grouping shortcuts. Fence windows automatically collapse into a thin panel when the cursor leaves their boundaries, and expand on hover, freeing up visual space. Magnetic snapping of fences to each other and to screen edges (with 20px precision) allows building a perfectly organized desktop without manual alignment.",
        "nesty_feat_title": "Key Features",
        "nesty_feat_1": "Automatic collapsing and expanding of fences on hover",
        "nesty_feat_2": "Magnetic snapping with 20px precision",
        "nesty_feat_3": "5 built-in neon design presets + custom preset via HEX code",
        "nesty_feat_4": "Safe file movement back to the desktop upon fence deletion",
        "nesty_feat_5": "Integration with Windows context menu and auto-start with the system",
        "nesty_feat_6": "Drag & Drop support",
        "nesty_feat_7": "Full installer for a few-clicks setup",
        "aether_subtitle": "Desktop AI assistant working as a semi-transparent overlay on all windows with audio capture and screen recognition.",
        "aether_problem": "During studies or work, students and professionals often lack a quick way to get a concise hint based on what they hear or see on the screen — without switching between windows and getting distracted from the main process.",
        "aether_solution": "Aether is a desktop AI assistant that acts as a semi-transparent overlay on top of all windows. The program captures audio from the microphone and transcribes it via Groq Whisper, and also recognizes text on the screen using Gemini Vision (OCR). The obtained data is sent to the Groq LLM, which generates a concise and accurate response right on the user's screen. A separate function makes the overlay invisible during screen sharing, allowing the use of the assistant discreetly.",
        "aether_feat_title": "Key Features",
        "aether_feat_1": "Real-time audio capture and transcription",
        "aether_feat_2": "OCR of a selected screen area",
        "aether_feat_3": "LLM response generation based on audio and visual data",
        "aether_feat_4": "Invisibility mode during screen sharing",
        "aether_feat_5": "Full set of hotkeys for control without interrupting the main task",
        "aether_feat_6": "Custom API key configuration (Groq, Gemini) directly in the app",
        "deckboard_subtitle": "Ecosystem consisting of an Android app and a Python PC server forming a complete remote control 'stream-deck'.",
        "deckboard_problem": "Controlling a computer during streams, presentations, or regular work often requires constant switching between keyboard and mouse for simple actions — muting the microphone, starting OBS recording, or opening a specific program.",
        "deckboard_solution": "DeckBoard is a two-part ecosystem: an Android app and a PC Python server, forming a complete remote control 'stream-deck'. Through the mobile app, the user controls audio, OBS recording, and launches any programs on the computer with a single touch, while the server is automatically discovered on the local network, making the connection virtually instant.",
        "deckboard_feat_title": "Key Features",
        "deckboard_feat_1": "Customized control tiles with Drag & Drop support",
        "deckboard_feat_2": "Automatic server discovery in the local network or manual IP connection",
        "deckboard_feat_3": "System audio and microphone control with a single touch",
        "deckboard_feat_4": "Remote start/stop recording via OBS WebSocket integration",
        "deckboard_feat_5": "Launch of arbitrary programs and shortcuts (.exe, .lnk, .url) from the system tray",
        "deckboard_feat_6": "Modular repository structure (separate Android client and PC server)",
        "androidcalc_subtitle": "Mobile calculator app for Android, developed for the Kharkiv Water Utility company.",
        "androidcalc_problem": "The client — Kharkiv Water Utility — needed a reliable, ready-to-integrate mobile calculator with a modern interface for internal use.",
        "androidcalc_solution": "AndroidCalc is a completed mobile calculator app for Android, developed by order of the Kharkiv Water Utility. The project implements a full set of basic mathematical operations in clean, well-documented code, ready for further feature expansion and integration into the client's larger systems.",
        "androidcalc_feat_title": "Key Features",
        "androidcalc_feat_1": "Developed by order of the Kharkiv Water Utility",
        "androidcalc_feat_2": "Modern and responsive UI/UX design",
        "androidcalc_feat_3": "Full support for basic mathematical operations",
        "androidcalc_feat_4": "Adaptability for different screen resolutions",
        "androidcalc_feat_5": "Clean, documented code, ready for expansion and integration",
        "homecinema_subtitle": "Local media server connecting Android TVs with Network Attached Storage (NAS) in a home network.",
        "homecinema_problem": "Commercial streaming services depend on internet connection, subscriptions, and external servers, while many users have their own media library and want to watch it on their TV without delays and third-party restrictions.",
        "homecinema_solution": "HomeCinema is a local media server connecting Android TVs with Network Attached Storage (NAS) in a home network. The project recreates the familiar experience of popular streaming platforms — a convenient catalog, covers, descriptions — but completely locally, without delays and dependence on external servers. The web admin panel allows easy library replenishment, and movie metadata is pulled automatically.",
        "homecinema_feat_title": "Key Features",
        "homecinema_feat_1": "Web admin panel for uploading and managing the movie library",
        "homecinema_feat_2": "Automatic pulling of covers, descriptions, and metadata",
        "homecinema_feat_3": "Android TV interface tailored for remote control",
        "homecinema_feat_4": "Completely local operation without delays and cloud service dependency",

        "nav_home": "Home",
        "nav_spec": "Specialization",
        "nav_services": "Services",
        "nav_process": "Workflow",
        "nav_about": "About",
        "nav_projects": "Projects",
        "nav_status": "Status",
        "services_title_1": "My",
        "services_title_2": "Services",
        "services_subtitle": "What I can build for you",
        "srv_desktop_title": "Desktop App Development",
        "srv_desktop_desc": "I build custom utilities and tools for Windows — from automating routine tasks to apps with a tailored interface.",
        "srv_desktop_f1": "Custom UI (PyQt6, Electron, WPF/C#)",
        "srv_desktop_f2": "Task automation & system scripts",
        "srv_desktop_f3": "Windows API & Registry integration",
        "srv_desktop_f4": "Ready for distribution (.exe, installers)",
        "srv_bots_title": "AI-Integrated Telegram Bots",
        "srv_bots_desc": "I write bots that go beyond basic commands — from simple automation to full-fledged AI assistants.",
        "srv_bots_f1": "Voice recognition (Whisper / Groq)",
        "srv_bots_f2": "LLM Integration (GPT, Groq, Gemini)",
        "srv_bots_f3": "Natural Language Processing & NLP scenarios",
        "srv_bots_f4": "Business funnels & auto-replies",
        "srv_android_title": "Android Applications",
        "srv_android_desc": "Mobile app development for Android — from simple utilities to apps integrating external services.",
        "srv_android_f1": "Native development (Kotlin / Java)",
        "srv_android_f2": "External API & services integration",
        "srv_android_f3": "Adaptive UI/UX for various screens",
        "srv_android_f4": "Ready for Play Store publication",
        "srv_auto_title": "Process Automation",
        "srv_auto_desc": "Parsers, data processing scripts, integrations — routine tasks run without manual intervention.",
        "srv_auto_f1": "Web scraping & parsers (BeautifulSoup, Selenium)",
        "srv_auto_f2": "Data processing & transformation (Excel, JSON, CSV)",
        "srv_auto_f3": "API & services integrations",
        "srv_auto_f4": "Scheduled tasks & background processes",
        "srv_consult_title": "Consulting & Refinement",
        "srv_consult_desc": "Helping bring your project to perfection, regardless of the stage: from code audit to architecture recommendations.",
        "srv_consult_f1": "Code review & codebase audit",
        "srv_consult_f2": "Bug fixing & refactoring",
        "srv_consult_f3": "Architectural recommendations",
        "srv_consult_f4": "Help finalizing MVP for production",
        "hero_badge": "Open to Work",
        "hero_title_1": "Building",
        "hero_title_2": "reliable",
        "hero_title_3": "software solutions",
        "hero_subtitle": "Architecture, development, and automation. From OS utilities to smart mobile apps and AI integrations.",
        "btn_contact_tg": "Message on Telegram",
        "btn_watch_projects": "View Projects",
        "spec_title_1": "My",
        "spec_title_2": "Specialization",
        "spec_subtitle": "Key areas where I bring the most value",
        "spec_desktop": "Desktop Tools",
        "spec_desktop_desc": "Native and cross-platform utilities development (Python/PyQt6, Electron).",
        "spec_mobile": "Mobile Apps",
        "spec_mobile_desc": "Native Android development (Kotlin, Java) and hardware integration.",
        "spec_ai": "AI Integration",
        "spec_ai_desc": "LLM models deployment, data parsing, and smart assistants creation.",
        "spec_auto": "Automation",
        "spec_auto_desc": "Scripts, bots, and web scrapers to automate routine business tasks.",
        "proj_title_1": "My",
        "proj_title_2": "Creations",
        "proj_subtitle": "Selected projects with detailed architecture descriptions",
        "filter_all": "All",
        "filter_desktop": "Desktop",
        "filter_mobile": "Mobile",
        "filter_ai": "AI / LLM",
        "btn_details": "Details",
        "status_dev": "In Development",
        "desc_nesty": "Stylish utility for Windows. Allows creating 'fences' to group desktop shortcuts.",
        "desc_aether": "Desktop AI assistant with audio capture (Groq Whisper) and screen recognition over all windows.",
        "desc_aitrainer": "Tool for deep learning. Analyzes material via AI and generates personalized tests.",
        "desc_deckboard": "PC control ecosystem from smartphone. OBS scene switching, macros, and auto-run.",
        "desc_homecinema": "Custom local media server. Convenient web admin and Android TV client.",
        "workflow_title_1": "My",
        "workflow_title_2": "Workflow",
        "workflow_subtitle": "Transparent and understandable approach to product development",
        "step1_title": "Discussion",
        "step1_desc": "Task analysis, optimal tech stack selection, and tech spec creation.",
        "step2_title": "MVP / Prototype",
        "step2_desc": "Fast creation of a basic version to test hypotheses and mechanics.",
        "step3_title": "Refinement",
        "step3_desc": "Design integration, feature addition, bug fixing, and code optimization.",
        "step4_title": "Support",
        "step4_desc": "Code handover, writing documentation, and deployment consultations.",
        "about_title_1": "About",
        "about_title_2": "Me",
        "about_role": "Vladislav / Developer",
        "about_bio": "I specialize in creating convenient, fast, and aesthetic software solutions. My goal is not just to write code, but to develop tools that truly solve user problems, whether it's desktop customization, AI-assisted learning, or business process automation.",
        "about_placeholder": "Photo placeholder (me.jpg)",
        "about_test1": "\"Slot for a future client review. Great project, done on time!\"",
        "about_test2": "\"Case study or another review that increases trust.\"",
        "status_title_1": "Currently",
        "status_title_2": "Working On",
        "status_subtitle": "Activity log and current project status",
        "time1_date": "2026-06-13",
        "time1_title": "> [DEV] HomeCinema",
        "time1_desc": "Writing web admin for local media server. Metadata autocomplete logic completed.",
        "time2_date": "2026-05-20",
        "time2_title": "> [TEST] Aether",
        "time2_desc": "LLM and OCR integration in desktop assistant. Screen recognition successfully passes QA.",
        "time3_date": "2026-04-15",
        "time3_title": "> [RELEASE] DeckBoard 1.0",
        "time3_desc": "Kotlin + Python stack released. Stable work on Windows and Android.",
        "cta_title": "Ready to discuss a task?",
        "cta_desc": "Tell me about your idea, and we'll find the best technical solution to implement it.",
        "cta_email": "Send Email",
        "footer_rights": "&copy; 2026 Владислав.",
        "back_to_portfolio": "← Back to Portfolio",
        "nesty_subtitle_full": "Stylish and lightweight Windows utility created for perfect desktop organization.",
        "label_platform": "Platform:",
        "label_tech": "Technologies:",
        "nesty_feat_title": " Key Features",
        "nesty_feat_1": "<strong> Smart Collapse:</strong> Windows automatically collapse into a thin header when the mouse leaves them, and smoothly expand on hover.",
        "nesty_feat_2": "<strong> Magnetic Snapping:</strong> Fences neatly snap to each other and screen edges (20px distance) for pixel-perfect organization.",
        "nesty_feat_3": "<strong> Deep Customization:</strong> 5 built-in neon presets (Blue, Purple, Green, Orange, Red) + ability to create custom presets via HEX color palette.",
        "nesty_feat_4": "<strong> File Safety:</strong> When deleting a fence, all files inside are automatically and safely moved back to the Desktop.",
        "nesty_feat_5": "<strong> Windows Integration:</strong> Adds 'Create Fence' directly to desktop context menu and auto-starts with system.",
        "nesty_feat_6": "<strong> Drag & Drop:</strong> Easily drag and drop files into the fence with standard mouse movement.",
        "nesty_install_title": " Installation",
        "nesty_install_desc": "Since the program is packed into a full installer, setup takes just a few clicks:",
        "nesty_install_1": "Run the <code>Nestly_Setup.exe</code> file.",
        "nesty_install_2": "Follow the on-screen instructions. The installer will add it to Auto-start and context menu automatically.",
        "nesty_install_3": "Done! The program is already running in the background.",
        "nesty_dev_title": " For Developers (Build from source)",
        "btn_github": "View on GitHub",
        "screen_1": "Screen 1",
        "screen_2": "Screen 2",
        "screen_3": "Screen 3",
        "screen_4": "Screen 4",
        "video": "Video",
        "btn_repo_closed": "Repository is currently closed",
        "aether_subtitle": "Desktop AI assistant for students — a semi-transparent overlay on top of all windows with audio and screen capture.",
        "aether_feat_title": " Features",
        "aether_feat_1": "<strong> Audio capture:</strong> microphone recording + transcription via Whisper (Groq API).",
        "aether_feat_2": "<strong> Screen OCR:</strong> capture selected area + text recognition via Gemini Vision.",
        "aether_feat_3": "<strong> LLM answers:</strong> fast generation of concise, accurate answers via Groq LLM.",
        "aether_feat_4": "<strong> Invisibility:</strong> the overlay is completely invisible during screen sharing (Windows 10/11).",
        "aether_feat_5": "<strong> Hotkeys:</strong> control without distracting from the main process.",
        "aether_install_title": " Installation",
        "aether_hotkeys_title": " Hotkeys",
        "aether_hk_col1": "Combination",
        "aether_hk_col2": "Action",
        "aether_hk_1": "Hide/show overlay",
        "aether_hk_2": "Enable/disable audio recording",
        "aether_hk_3": "Take a screenshot of an area",
        "aether_hk_4": "Toggle invisibility for screen sharing",
        "aether_hk_5": "Exit application",
        "aether_api_title": " API Keys",
        "aether_api_desc": "Free API keys are required to work:",
        "aether_api_1": "<strong>Groq API</strong> — console.groq.com (STT + LLM, free)",
        "aether_api_2": "<strong>Google Gemini API</strong> — aistudio.google.com (OCR, free)",
        "aether_api_footer": "Keys are entered in the application settings ( icon).",
        "ai_trainer_subtitle": "A powerful tool for deep and productive learning of any information using AI.",
        "ai_trainer_concept_title": "Idea and working principle",
        "ai_trainer_concept_p1": "AI Trainer was originally developed by students for students to simplify deep learning of heavy information. However, its working principle makes it possible to use it in any field for absolutely any person regardless of their level of knowledge.",
        "ai_trainer_concept_p2": "At the core of assembling all tests is an AI that analyzes your given material, and based on it compiles a certain number of questions with different answer formats. All executable models available to you in the application are part of the free non-commercial library <code>g4f</code>, which allows you to use a mass of closed models without restrictions.",
        "ai_trainer_tech_title": "Technical details",
        "ai_trainer_tech_p1": "Using the asynchronous wrapper of the <code>AIClient</code> class, you can access multiple models simultaneously, or in different chats, without blocking the main execution thread.",
        "ai_trainer_tech_p2": "<strong>Important note:</strong> Please do not increase limits such as <code>ThreadPoolExecutor(max_workers=4)</code> or <code>max_tokens=1200</code> so as not to overload provider servers excessively.",
        "ai_trainer_lang_title": "Localization",
        "deckboard_subtitle": "A powerful ecosystem for remote control of your computer directly from your smartphone.",
        "deckboard_feat_title": " Main features",
        "deckboard_android_title": " Android App (Client)",
        "deckboard_android_1": "<strong>Customization:</strong> Complete freedom of action with Drag-and-Drop support for sorting tiles.",
        "deckboard_android_2": "<strong>Intuitiveness:</strong> Modern interface with smooth animation and feedback.",
        "deckboard_android_3": "<strong>Smart connection:</strong> Automatic server search in the local network or manual IP entry with saving.",
        "deckboard_pc_title": " PC Server (Python)",
        "deckboard_pc_1": "<strong>Audio control:</strong> Quick toggle of microphone mute and system sound (Speakers).",
        "deckboard_pc_2": "<strong>OBS Integration:</strong> Remote start and stop of recording via WebSocket.",
        "deckboard_pc_3": "<strong>Launch software:</strong> Ability to add any shortcuts (.exe, .lnk, .url) right from the system tray.",
        "deckboard_pc_4": "<strong>Convenience:</strong> The current server IP address is always visible in the tray menu for quick setup.",
        "deckboard_structure_title": " Project structure",
        "deckboard_structure_desc": "The repository is divided into two logical parts:",
        "deckboard_structure_1": "<code>/AndroidApp</code> — Source code of the mobile application (Kotlin/Android Studio).",
        "deckboard_structure_2": "<code>/pc-server</code> — Server part on Python using Flask and PyStray.",
        "deckboard_stack_title": " Tech stack",
        "deckboard_stack_1": "<strong>Android:</strong> Kotlin, Retrofit2, SharedPreferences, ItemTouchHelper.",
        "deckboard_stack_2": "<strong>Backend:</strong> Python, Flask, OBS-WebSocket, PyCaw, PyStray, NirCmd.",
        "homecinema_badge": "In active development",
        "homecinema_subtitle": "Your own local home cinema connecting Android TV with network storage.",
        "homecinema_concept_title": "Concept",
        "homecinema_concept_p1": "HomeCinema is a project that connects Android-based TVs with a local network-attached storage (NAS) in your home network, allowing you to comfortably watch movies and series.",
        "homecinema_concept_p2": "The design and user experience (UX) are inspired by popular streaming services, but operate completely locally and without delays.",
        "homecinema_feat_title": "Key features (Current build)",
        "homecinema_feat_1": "<strong>Custom Admin Panel:</strong> A convenient web interface through which it's easy to upload new movies to the library.",
        "homecinema_feat_2": "<strong>Smart autocomplete:</strong> When adding a movie, covers, descriptions, and metadata are pulled automatically.",
        "homecinema_feat_3": "<strong>Smooth UI for Android TV:</strong> The interface is specifically adapted for control from the TV remote.",
        "homecinema_note": "The project is currently not published on GitHub as it is in active development, but already has a fully working build."
    },
    "ru": {
        "desc_nesty": "Легковесная утилита для Windows, которая вводит систему «сеток» (Fences) для группировки ярлыков.",
        "desc_aether": "Десктопный AI-ассистент, работающий как полупрозрачный overlay поверх всех окон с захватом аудио и распознаванием экрана.",
        "desc_deckboard": "Экосистема из Android-приложения и Python-сервера на ПК, образующих полноценную «стрим-панель».",
        "desc_androidcalc": "Мобильное приложение-калькулятор для Android, разработанное по заказу Харьковского водоканала.",
        "desc_homecinema": "Локальный медиасервер, объединяющий телевизоры на Android TV с сетевым хранилищем (NAS).",
        "problem_title": "Проблема",
        "solution_title": "Решение",
        "nesty_subtitle_full": "Легковесная утилита для Windows, которая вводит систему «сеток» (Fences) для группировки ярлыков.",
        "nesty_problem": "Стандартный рабочий стол Windows быстро превращается в хаотичное нагромождение ярлыков и файлов, а встроенные инструменты системы не дают гибких способов организовать пространство под себя.",
        "nesty_solution": "Nestly — легковесная утилита для Windows, которая вводит систему «сеток» (Fences) для группировки ярлыков. Окна сеток автоматически сворачиваются в тонкую панель, когда курсор покидает их пределы, и разворачиваются при наведении, освобождая визуальное пространство. Магнитное прилипание сеток друг к другу и к краям экрана (с точностью до 20 пикселей) позволяет выстроить идеально упорядоченный рабочий стол без ручного выравнивания.",
        "nesty_feat_title": "Ключевые особенности",
        "nesty_feat_1": "Автоматическое сворачивание и разворачивание сеток при наведении курсора",
        "nesty_feat_2": "Магнитное прилипание (snapping) с точностью 20 px",
        "nesty_feat_3": "5 встроенных неоновых пресетов оформления + собственный пресет по HEX-коду",
        "nesty_feat_4": "Безопасное перемещение файлов обратно на рабочий стол при удалении сетки",
        "nesty_feat_5": "Интеграция с контекстным меню Windows и автозапуск вместе с системой",
        "nesty_feat_6": "Поддержка Drag & Drop",
        "nesty_feat_7": "Полноценный инсталлятор для установки в пару кликов",
        "aether_subtitle": "Десктопный AI-ассистент, работающий как полупрозрачный overlay поверх всех окон с захватом аудио и распознаванием экрана.",
        "aether_problem": "Во время учебы или работы студентам и специалистам часто не хватает быстрого способа получить краткую подсказку на основе того, что они слышат или видят на экране, — без переключения между окнами и отвлечения от основного процесса.",
        "aether_solution": "Aether — десктопный AI-ассистент, работающий как полупрозрачный overlay поверх всех окон. Программа захватывает аудио с микрофона и транскрибирует его через Groq Whisper, а также распознает текст на экране с помощью Gemini Vision (OCR). Полученные данные передаются в Groq LLM, который генерирует краткий и точный ответ прямо на экране пользователя. Отдельная функция делает overlay невидимым во время демонстрации экрана, что позволяет использовать ассистента незаметно.",
        "aether_feat_title": "Ключевые особенности",
        "aether_feat_1": "Захват и транскрипция аудио в реальном времени",
        "aether_feat_2": "OCR выбранной области экрана",
        "aether_feat_3": "Генерация ответов через LLM на основе аудио и визуальных данных",
        "aether_feat_4": "Режим невидимости во время демонстрации экрана",
        "aether_feat_5": "Полный набор горячих клавиш для управления без отрыва от основной задачи",
        "aether_feat_6": "Настройка собственных API-ключей (Groq, Gemini) непосредственно в программе",
        "deckboard_subtitle": "Экосистема из Android-приложения и Python-сервера на ПК, образующих полноценную «стрим-панель» дистанционного управления.",
        "deckboard_problem": "Управление компьютером во время стримов, презентаций или обычной работы часто требует постоянного переключения между клавиатурой и мышью для простых действий — выключения микрофона, запуска записи в OBS или открытия нужной программы.",
        "deckboard_solution": "DeckBoard — экосистема из двух частей: Android-приложение и Python-сервер на ПК, которые образуют полноценную «стрим-панель» дистанционного управления. Через мобильное приложение пользователь одним касанием управляет звуком, записью в OBS и запуском любых программ на компьютере, а сервер автоматически обнаруживается в локальной сети, что делает подключение практически мгновенным.",
        "deckboard_feat_title": "Ключевые особенности",
        "deckboard_feat_1": "Кастомизированные плитки управления с поддержкой Drag & Drop",
        "deckboard_feat_2": "Автоматический поиск сервера в локальной сети или ручное подключение по IP",
        "deckboard_feat_3": "Управление системным звуком и микрофоном одним касанием",
        "deckboard_feat_4": "Дистанционный старт/стоп записи через интеграцию с OBS WebSocket",
        "deckboard_feat_5": "Запуск произвольных программ и ярлыков (.exe, .lnk, .url) из системного трея",
        "deckboard_feat_6": "Модульная структура репозитория (отдельно Android-клиент и PC-сервер)",
        "androidcalc_subtitle": "Мобильное приложение-калькулятор для Android, разработанное по заказу Харьковского водоканала.",
        "androidcalc_problem": "Заказчику — Харьковскому водоканалу — нужен был надежный, готовый к интеграции мобильный калькулятор с современным интерфейсом для внутреннего использования.",
        "androidcalc_solution": "AndroidCalc — завершенное мобильное приложение-калькулятор для Android, разработанное по заказу Харьковского водоканала. Проект реализует полный набор базовых математических операций в чистом, хорошо задокументированном коде, готовом к дальнейшему расширению функционала и интеграции в большие системы заказчика.",
        "androidcalc_feat_title": "Ключевые особенности",
        "androidcalc_feat_1": "Разработано по заказу Харьковского водоканала",
        "androidcalc_feat_2": "Современный и отзывчивый UI/UX дизайн",
        "androidcalc_feat_3": "Полная поддержка базовых математических операций",
        "androidcalc_feat_4": "Адаптивность под разные разрешения экрана",
        "androidcalc_feat_5": "Чистый, документированный код, готовый к расширению и интеграции",
        "homecinema_subtitle": "Локальный медиасервер, объединяющий телевизоры на Android TV с сетевым хранилищем (NAS) в домашней сети.",
        "homecinema_problem": "Коммерческие стриминговые сервисы зависят от интернет-соединения, подписок и внешних серверов, в то время как многие пользователи имеют собственную медиатеку и хотят просматривать ее на телевизоре без задержек и сторонних ограничений.",
        "homecinema_solution": "HomeCinema — локальный медиасервер, объединяющий телевизоры на Android TV с сетевым хранилищем (NAS) в домашней сети. Проект воссоздает привычный опыт популярных стриминговых платформ — удобный каталог, обложки, описания — но полностью локально, без задержек и зависимости от внешних серверов. Веб-админка позволяет легко пополнять библиотеку, а метаданные фильмов подтягиваются автоматически.",
        "homecinema_feat_title": "Ключевые особенности",
        "homecinema_feat_1": "Веб-админпанель для загрузки и управления библиотекой фильмов",
        "homecinema_feat_2": "Автоматическое подтягивание обложек, описаний и метаданных",
        "homecinema_feat_3": "Интерфейс для Android TV, адаптированный под управление пультом",
        "homecinema_feat_4": "Полностью локальная работа без задержек и зависимости от облачных сервисов",

        "nav_home": "Главная",
        "nav_spec": "Специализация",
        "nav_services": "Услуги",
        "nav_process": "Процесс",
        "nav_about": "Обо мне",
        "nav_projects": "Проекты",
        "nav_status": "Статус",
        "services_title_1": "Мои",
        "services_title_2": "Услуги",
        "services_subtitle": "Что именно я могу сделать для вас",
        "srv_desktop_title": "Разработка десктоп-приложений",
        "srv_desktop_desc": "Создаю кастомные утилиты и инструменты под Windows — от автоматизации рутинных задач до приложений с собственным интерфейсом.",
        "srv_desktop_f1": "Кастомный UI (PyQt6, Electron, WPF/C#)",
        "srv_desktop_f2": "Автоматизация задач и системные скрипты",
        "srv_desktop_f3": "Интеграция с Windows API и реестром",
        "srv_desktop_f4": "Готовы к дистрибуции (.exe, инсталляторы)",
        "srv_bots_title": "Telegram-боты с интеграцией AI",
        "srv_bots_desc": "Пишу ботов, которые умеют больше стандартных команд — от простой автоматизации до полноценных AI-ассистентов.",
        "srv_bots_f1": "Распознавание голоса (Whisper / Groq)",
        "srv_bots_f2": "Интеграция с LLM (GPT, Groq, Gemini)",
        "srv_bots_f3": "Обработка естественного языка и NLP-сценарии",
        "srv_bots_f4": "Бизнес-воронки и автоответы",
        "srv_android_title": "Android-приложения",
        "srv_android_desc": "Разработка мобильных приложений под Android — от простых утилит до приложений с интеграцией внешних сервисов.",
        "srv_android_f1": "Нативная разработка (Kotlin / Java)",
        "srv_android_f2": "Интеграция с внешними API и сервисами",
        "srv_android_f3": "Адаптивный UI/UX под разные экраны",
        "srv_android_f4": "Готово к публикации в Play Store",
        "srv_auto_title": "Автоматизация процессов",
        "srv_auto_desc": "Парсеры, скрипты обработки данных, интеграции между сервисами — рутинные задачи выполняются без ручного вмешательства.",
        "srv_auto_f1": "Веб-скрапинг и парсеры (BeautifulSoup, Selenium)",
        "srv_auto_f2": "Обработка и трансформация данных (Excel, JSON, CSV)",
        "srv_auto_f3": "Интеграции между API и сервисами",
        "srv_auto_f4": "Scheduled-задачи и фоновые процессы",
        "srv_consult_title": "Консультации и доработка",
        "srv_consult_desc": "Помогаю довести проект до ума — независимо от стадии: от аудита кода до архитектурных рекомендаций.",
        "srv_consult_f1": "Code review и аудит кодовой базы",
        "srv_consult_f2": "Исправление багов и рефакторинг",
        "srv_consult_f3": "Архитектурные рекомендации",
        "srv_consult_f4": "Помощь с доработкой MVP до продакшна",
        "hero_badge": "Открыт для проектов и предложений",
        "hero_title_1": "Создаю",
        "hero_title_2": "надежные",
        "hero_title_3": "программные решения",
        "hero_subtitle": "Архитектура, разработка и автоматизация. От утилит для ОС до умных мобильных приложений и AI-интеграций.",
        "btn_contact_tg": "Написать в Telegram",
        "btn_watch_projects": "Смотреть проекты",
        "spec_title_1": "Моя",
        "spec_title_2": "Специализация",
        "spec_subtitle": "Ключевые направления, в которых я приношу максимальную пользу",
        "spec_desktop": "Desktop Tools",
        "spec_desktop_desc": "Разработка нативных и кроссплатформенных утилит (Python/PyQt6, Electron).",
        "spec_mobile": "Mobile Apps",
        "spec_mobile_desc": "Нативная разработка под Android (Kotlin, Java) и интеграция с железом.",
        "spec_ai": "AI Integration",
        "spec_ai_desc": "Внедрение LLM моделей, парсинг данных и создание умных ассистентов.",
        "spec_auto": "Automation",
        "spec_auto_desc": "Скрипты, боты и веб-парсеры для автоматизации рутинных бизнес-задач.",
        "proj_title_1": "Мои",
        "proj_title_2": "Творения",
        "proj_subtitle": "Избранные проекты с подробным описанием архитектуры",
        "filter_all": "Все",
        "filter_desktop": "Desktop",
        "filter_mobile": "Mobile",
        "filter_ai": "AI / LLM",
        "btn_details": "Подробнее",
        "status_dev": "В разработке",
        "desc_nesty": "Стильная утилита для Windows. Позволяет создавать 'сетки' для группировки ярлыков на рабочем столе.",
        "desc_aether": "Десктопный AI-ассистент с захватом аудио (Groq Whisper) и распознаванием экрана поверх всех окон.",
        "desc_aitrainer": "Инструмент для глубокого обучения. Анализирует материал через AI и генерирует персональные тесты.",
        "desc_deckboard": "Экосистема для управления ПК со смартфона. Переключение сцен OBS, макросы и автозапуск.",
        "desc_homecinema": "Собственный локальный медиасервер. Удобная веб-админка и клиент под Android TV.",
        "workflow_title_1": "Процесс",
        "workflow_title_2": "Работы",
        "workflow_subtitle": "Прозрачный и понятный подход к разработке продуктов",
        "step1_title": "Обсуждение",
        "step1_desc": "Анализ задачи, подбор оптимального стека технологий и составление ТЗ.",
        "step2_title": "MVP / Прототип",
        "step2_desc": "Быстрое создание базовой версии для тестирования гипотез и механик.",
        "step3_title": "Доработка",
        "step3_desc": "Интеграция дизайна, добавление фич, отлов багов и оптимизация кода.",
        "step4_title": "Поддержка",
        "step4_desc": "Передача готового кода, написание инструкций и консультации по деплою.",
        "about_title_1": "Обо",
        "about_title_2": "Мне",
        "about_role": "Владислав / Разработчик",
        "about_bio": "Я специализируюсь на создании удобных, быстрых и эстетичных программных решений. Моя цель — не просто писать код, а разрабатывать инструменты, которые действительно решают проблемы пользователей, будь то кастомизация рабочего стола, обучение с помощью AI или автоматизация бизнес-процессов.",
        "about_placeholder": "Заглушка фото (me.jpg)",
        "about_test1": "\"Слот для будущего отзыва заказчика. Отличный проект, сделано в срок!\"",
        "about_test2": "\"Кейс-стади или еще один отзыв, повышающий доверие.\"",
        "status_title_1": "Сейчас в",
        "status_title_2": "Работе",
        "status_subtitle": "Лог активности и актуальный статус проектов",
        "time1_date": "2026-06-13",
        "time1_title": "> [DEV] HomeCinema",
        "time1_desc": "Пишу веб-админку для локального медиасервера. Завершена логика автозаполнения метаданных.",
        "time2_date": "2026-05-20",
        "time2_title": "> [TEST] Aether",
        "time2_desc": "Интеграция LLM и OCR в десктопный ассистент. Распознавание экрана успешно проходит QA.",
        "time3_date": "2026-04-15",
        "time3_title": "> [RELEASE] DeckBoard 1.0",
        "time3_desc": "Связка Kotlin + Python отправлена в релиз. Стабильная работа на Windows и Android.",
        "cta_title": "Готовы обсудить задачу?",
        "cta_desc": "Расскажите о вашей идее, и мы найдем лучшее техническое решение для ее реализации.",
        "cta_email": "Отправить Email",
        "footer_rights": "&copy; 2026 Владислав.",
        "back_to_portfolio": "← Назад в Портфолио",
        "nesty_subtitle_full": "Стильная и легковесная утилита для Windows, созданная для идеального порядка на рабочем столе.",
        "label_platform": "Платформа:",
        "label_tech": "Технологии:",
        "nesty_feat_title": " Главные фишки",
        "nesty_feat_1": "<strong> Умное сворачивание:</strong> Окна автоматически сворачиваются в тонкую шапку, когда мышь уходит за их пределы, и плавно разворачиваются при наведении.",
        "nesty_feat_2": "<strong> Магнитное прилипание (Snapping):</strong> Сетки аккуратно магнитятся друг к другу и к краям экрана (дистанция 20 пикселей) для создания идеального пиксельного порядка.",
        "nesty_feat_3": "<strong> Глубокая кастомизация:</strong> 5 встроенных неоновых пресетов (Синий, Фиолетовый, Зеленый, Оранжевый, Красный) + возможность создать свой собственный пресет по HEX-коду через встроенную палитру.",
        "nesty_feat_4": "<strong> Безопасность файлов:</strong> При удалении сетки все файлы из неё автоматически и безопасно перемещаются обратно на Рабочий стол.",
        "nesty_feat_5": "<strong> Интеграция с Windows:</strong> Программа добавляет пункт \"Создать Сетку (Fences)\" прямо в контекстное меню рабочего стола и автоматически запускается вместе с системой.",
        "nesty_feat_6": "<strong> Drag & Drop:</strong> Файлы легко перетаскиваются внутрь сетки обычным движением мыши.",
        "nesty_install_title": " Установка",
        "nesty_install_desc": "Поскольку программа упакована в полноценный инсталлятор, установка занимает всего пару кликов:",
        "nesty_install_1": "Запустите файл <code>Nestly_Setup.exe</code>.",
        "nesty_install_2": "Следуйте инструкциям на экране. Установщик автоматически добавит программу в Автозагрузку и пропишет контекстное меню.",
        "nesty_install_3": "Готово! Программа уже работает в фоновом режиме.",
        "nesty_dev_title": " Для разработчиков (Сборка из исходников)",
        "btn_github": "Посмотреть на GitHub",
        "screen_1": "Скрин 1",
        "screen_2": "Скрин 2",
        "screen_3": "Скрин 3",
        "screen_4": "Скрин 4",
        "video": "Видео",
        "btn_repo_closed": "Репозиторий пока закрыт",

        "aether_subtitle": "Десктопный AI-ассистент для студентов — полупрозрачный overlay поверх всех окон с захватом аудио и экрана.",
        "aether_feat_title": " Возможности",
        "aether_feat_1": "<strong> Захват аудио:</strong> запись с микрофона + транскрипция через Whisper (Groq API).",
        "aether_feat_2": "<strong> OCR экрана:</strong> скриншот выбранной области + распознавание текста через Gemini Vision.",
        "aether_feat_3": "<strong> LLM ответы:</strong> быстрая генерация кратких, точных ответов через Groq LLM.",
        "aether_feat_4": "<strong> Невидимость:</strong> overlay полностью невидим при демонстрации экрана (Windows 10/11).",
        "aether_feat_5": "<strong> Горячие клавиши:</strong> управление без отвлечения от основного процесса.",
        "aether_install_title": " Установка",
        "aether_hotkeys_title": " Горячие клавиши",
        "aether_hk_col1": "Комбинация",
        "aether_hk_col2": "Действие",
        "aether_hk_1": "Скрыть/показать overlay",
        "aether_hk_2": "Включить/выключить запись аудио",
        "aether_hk_3": "Сделать скриншот области",
        "aether_hk_4": "Переключить невидимость для демонстрации экрана",
        "aether_hk_5": "Выход из приложения",
        "aether_api_title": " API Ключи",
        "aether_api_desc": "Для работы необходимы бесплатные API-ключи:",
        "aether_api_1": "<strong>Groq API</strong> — console.groq.com (STT + LLM, бесплатно)",
        "aether_api_2": "<strong>Google Gemini API</strong> — aistudio.google.com (OCR, бесплатно)",
        "aether_api_footer": "Ключи вводятся в настройках приложения (иконка ).",

        "ai_trainer_subtitle": "Мощный инструмент для глубокого и продуктивного обучения любой информации с использованием AI.",
        "ai_trainer_concept_title": "Идея и принцип работы",
        "ai_trainer_concept_p1": "AI Trainer изначально разрабатывался студентами для студентов в целях упростить глубокое обучение тяжёлой информации. Однако принцип его работы делает возможным его использование в любой сфере для абсолютно любого человека в независимости от уровня его знаний.",
        "ai_trainer_concept_p2": "В основе сборки всех тестов лежит ИИ, который анализирует заданный Вами материал, и на его основе составляет определённое количество вопросов с разными форматами ответов. Все исполняемые модели, которые доступны Вам в приложении являются частью бесплатной некоммерческой библиотеки <code>g4f</code>, которая позволяет использовать массу закрытых моделей без ограничений.",
        "ai_trainer_tech_title": "Технические детали",
        "ai_trainer_tech_p1": "С помощью асинхронной оболочки класса <code>AIClient</code> Вы можете обращаться сразу к нескольким моделями одновременно, либо же в разных чатах, при этом не блокируя основной поток выполнения.",
        "ai_trainer_tech_p2": "<strong>Важное примечание:</strong> Просим не повышать значения лимитов, таких как <code>ThreadPoolExecutor(max_workers=4)</code> или <code>max_tokens=1200</code>, чтобы чрезмерно не перегружать сервера провайдеров.",
        "ai_trainer_lang_title": "Локализация",

        "deckboard_subtitle": "Мощная экосистема для дистанционного управления вашим компьютером прямо со смартфона.",
        "deckboard_feat_title": " Основные возможности",
        "deckboard_android_title": " Android Приложение (Client)",
        "deckboard_android_1": "<strong>Кастомизация:</strong> Полная свобода действий с поддержкой Drag-and-Drop для сортировки плиток.",
        "deckboard_android_2": "<strong>Интуитивность:</strong> Современный интерфейс с плавной анимацией и обратной связью.",
        "deckboard_android_3": "<strong>Умное подключение:</strong> Автоматический поиск сервера в локальной сети или ручной ввод IP с сохранением.",
        "deckboard_pc_title": " PC Сервер (Python)",
        "deckboard_pc_1": "<strong>Управление звуком:</strong> Быстрое переключение мута микрофона и системного звука (Speakers).",
        "deckboard_pc_2": "<strong>Интеграция с OBS:</strong> Дистанционный запуск и остановка записи через WebSocket.",
        "deckboard_pc_3": "<strong>Запуск софта:</strong> Возможность добавлять любые ярлыки (.exe, .lnk, .url) прямо из системного трея.",
        "deckboard_pc_4": "<strong>Удобство:</strong> Текущий IP-адрес сервера всегда виден в меню трея для быстрой настройки.",
        "deckboard_structure_title": " Структура проекта",
        "deckboard_structure_desc": "Репозиторий разделен на две логические части:",
        "deckboard_structure_1": "<code>/AndroidApp</code> — Исходный код мобильного приложения (Kotlin/Android Studio).",
        "deckboard_structure_2": "<code>/pc-server</code> — Серверная часть на Python с использованием Flask и PyStray.",
        "deckboard_stack_title": " Технологический стек",
        "deckboard_stack_1": "<strong>Android:</strong> Kotlin, Retrofit2, SharedPreferences, ItemTouchHelper.",
        "deckboard_stack_2": "<strong>Backend:</strong> Python, Flask, OBS-WebSocket, PyCaw, PyStray, NirCmd.",

        "homecinema_badge": "В активной разработке",
        "homecinema_subtitle": "Собственный локальный домашний кинотеатр, связывающий Android TV с сетевым хранилищем.",
        "homecinema_concept_title": "Концепция",
        "homecinema_concept_p1": "HomeCinema — это проект, который связывает телевизоры на базе Android с локальным хранилищем (NAS) в домашней сети, позволяя с комфортом смотреть фильмы и сериалы.",
        "homecinema_concept_p2": "Оформление и пользовательский опыт (UX) вдохновлены популярными стриминговыми сервисами, но работают полностью локально и без задержек.",
        "homecinema_feat_title": "Ключевые фичи (Текущий билд)",
        "homecinema_feat_1": "<strong>Собственная Админ-панель:</strong> Удобный веб-интерфейс, через который легко загружать новые фильмы в библиотеку.",
        "homecinema_feat_2": "<strong>Умное автозаполнение:</strong> При добавлении фильма обложки, описания и метаданные подтягиваются автоматически.",
        "homecinema_feat_3": "<strong>Плавный UI для Android TV:</strong> Интерфейс адаптирован специально для управления с пульта ДУ телевизора.",
        "homecinema_note": "Проект на данный момент не опубликован на GitHub, так как находится в стадии активной разработки, но уже имеет полностью рабочий билд."
    }
};

document.addEventListener("DOMContentLoaded", () => {
    const langBtns = document.querySelectorAll('.lang-btn');
    const elementsToTranslate = document.querySelectorAll('[data-i18n]');
    
    const setLanguage = (lang) => {
        if (!translations[lang]) return;
        localStorage.setItem('portfolio_lang', lang);
        
        elementsToTranslate.forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[lang][key]) {
                el.innerHTML = translations[lang][key]; 
            }
        });
        
        langBtns.forEach(btn => {
            if (btn.dataset.lang === lang) {
                btn.classList.add('active');
            } else {
                btn.classList.remove('active');
            }
        });
    };

    const savedLang = localStorage.getItem('portfolio_lang') || 'uk';
    setLanguage(savedLang);

    langBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            setLanguage(btn.dataset.lang);
        });
    });

    const themeToggleBtns = document.querySelectorAll('.theme-toggle');
    const moonIcon = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>';
    const sunIcon = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>';

    const savedTheme = localStorage.getItem('portfolio_theme') || 'dark';
    if (savedTheme === 'light') {
        document.body.classList.add('light-theme');
    }

    const updateIcons = () => {
        const isLight = document.body.classList.contains('light-theme');
        themeToggleBtns.forEach(btn => {
            btn.innerHTML = isLight ? moonIcon : sunIcon;
        });
    }
    
    updateIcons();

    themeToggleBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            document.body.classList.toggle('light-theme');
            localStorage.setItem('portfolio_theme', document.body.classList.contains('light-theme') ? 'light' : 'dark');
            updateIcons();
        });
    });
});

