const translations = {
    "uk": {
        "nav_home": "Головна",
        "nav_spec": "Спеціалізація",
        "nav_process": "Процес",
        "nav_about": "Про мене",
        "nav_projects": "Проєкти",
        "nav_status": "Статус",
        "hero_badge": "Відкритий до проєктів та пропозицій",
        "hero_title_1": "Створюю",
        "hero_title_2": "надійні",
        "hero_title_3": "програмні рішення",
        "hero_subtitle": "Архітектура, розробка та автоматизація. Від утиліт для ОС до розумних мобільних додатків та AI-інтеграцій.",
        "btn_contact_tg": "Написати в Telegram",
        "btn_watch_projects": "Дивитись проєкти",
        "spec_title_1": "Моя",
        "spec_title_2": "Спеціалізація",
        "spec_subtitle": "Ключові напрямки, в яких я приношу максимальну користь",
        "spec_desktop": "Desktop Tools",
        "spec_desktop_desc": "Розробка нативних та кросплатформних утиліт (Python/PyQt6, Electron).",
        "spec_mobile": "Mobile Apps",
        "spec_mobile_desc": "Нативна розробка під Android (Kotlin, Java) та інтеграція з залізом.",
        "spec_ai": "AI Integration",
        "spec_ai_desc": "Впровадження LLM моделей, парсинг даних та створення розумних асистентів.",
        "spec_auto": "Automation",
        "spec_auto_desc": "Скрипти, боти та веб-парсери для автоматизації рутинних бізнес-задач.",
        "proj_title_1": "Мої",
        "proj_title_2": "Творіння",
        "proj_subtitle": "Вибрані проєкти з детальним описом архітектури",
        "filter_all": "Всі",
        "filter_desktop": "Desktop",
        "filter_mobile": "Mobile",
        "filter_ai": "AI / LLM",
        "btn_details": "Детальніше",
        "status_dev": "В розробці",
        "desc_nesty": "Стильна утиліта для Windows. Дозволяє створювати 'сітки' для групування ярликів на робочому столі.",
        "desc_aether": "Десктопний AI-асистент із захопленням аудіо (Groq Whisper) та розпізнаванням екрану поверх усіх вікон.",
        "desc_aitrainer": "Інструмент для глибокого навчання. Аналізує матеріал через AI та генерує персональні тести.",
        "desc_deckboard": "Екосистема для управління ПК зі смартфона. Перемикання сцен OBS, макроси та автозапуск.",
        "desc_androidcalc": "Сучасний додаток калькулятора для Android з розширеним функціоналом.",
        "desc_homecinema": "Власний локальний медіасервер. Зручна веб-адмінка та клієнт під Android TV.",
        "workflow_title_1": "Процес",
        "workflow_title_2": "Роботи",
        "workflow_subtitle": "Прозорий та зрозумілий підхід до розробки продуктів",
        "step1_title": "Обговорення",
        "step1_desc": "Аналіз завдання, підбір оптимального стеку технологій та складання ТЗ.",
        "step2_title": "MVP / Прототип",
        "step2_desc": "Швидке створення базової версії для тестування гіпотез та механік.",
        "step3_title": "Доробка",
        "step3_desc": "Інтеграція дизайну, додавання фіч, відлов багів та оптимізація коду.",
        "step4_title": "Підтримка",
        "step4_desc": "Передача готового коду, написання інструкцій та консультації по деплою.",
        "about_title_1": "Про",
        "about_title_2": "Мене",
        "about_role": "Владислав / Розробник",
        "about_bio": "Я спеціалізуюсь на створенні зручних, швидких та естетичних програмних рішень. Моя мета — не просто писати код, а розробляти інструменти, які дійсно вирішують проблеми користувачів, будь то кастомізація робочого столу, навчання за допомогою AI чи автоматизація бізнес-процесів.",
        "about_placeholder": "Заглушка фото (me.jpg)",
        "about_test1": "\"Слот для майбутнього відгуку замовника. Відмінний проєкт, зроблено вчасно!\"",
        "about_test2": "\"Кейс-стаді або ще один відгук, що підвищує довіру.\"",
        "status_title_1": "Зараз в",
        "status_title_2": "Роботі",
        "status_subtitle": "Лог активності та актуальний статус проєктів",
        "time1_date": "2026-06-13",
        "time1_title": "> [DEV] HomeCinema",
        "time1_desc": "Пишу веб-адмінку для локального медіасервера. Завершена логіка автозаповнення метаданих.",
        "time2_date": "2026-05-20",
        "time2_title": "> [TEST] Aether",
        "time2_desc": "Інтеграція LLM та OCR в десктопний асистент. Розпізнавання екрану успішно проходить QA.",
        "time3_date": "2026-04-15",
        "time3_title": "> [RELEASE] DeckBoard 1.0",
        "time3_desc": "Зв'язка Kotlin + Python відправлена в реліз. Стабільна робота на Windows та Android.",
        "cta_title": "Чи готові обговорити завдання?",
        "cta_desc": "Розкажіть про вашу ідею, і ми знайдемо найкраще технічне рішення для її реалізації.",
        "cta_email": "Відправити Email",
        "footer_rights": " 2026 Владислав. Створено з фокусом на UX.",
        "back_to_portfolio": "← Назад у Портфоліо",
        "nesty_subtitle_full": "Стильна та легковагова утиліта для Windows, створена для ідеального порядку на робочому столі.",
        "label_platform": "Платформа:",
        "label_tech": "Технології:",
        "nesty_feat_title": " Головні фішки",
        "nesty_feat_1": "<strong> Розумне згортання:</strong> Вікна автоматично згортаються в тонку шапку, коли миша залишає їх межі, і плавно розгортаються при наведенні.",
        "nesty_feat_2": "<strong> Магнітне прилипання (Snapping):</strong> Сітки акуратно магнітяться одна до одної та до країв екрану (дистанція 20 пікселів) для створення ідеального піксельного порядку.",
        "nesty_feat_3": "<strong> Глибока кастомізація:</strong> 5 вбудованих неонових пресетів (Синій, Фіолетовий, Зелений, Помаранчевий, Червоний) + можливість створити свій пресет за HEX-кодом через палітру.",
        "nesty_feat_4": "<strong> Безпека файлів:</strong> При видаленні сітки всі файли з неї автоматично і безпечно переміщуються назад на Робочий стіл.",
        "nesty_feat_5": "<strong> Інтеграція з Windows:</strong> Програма додає пункт \"Створити Сітку (Fences)\" прямо в контекстне меню робочого столу і автоматично запускається разом із системою.",
        "nesty_feat_6": "<strong> Drag & Drop:</strong> Файли легко перетягуються всередину сітки звичайним рухом миші.",
        "nesty_install_title": " Встановлення",
        "nesty_install_desc": "Оскільки програма запакована в повноцінний інсталятор, встановлення займає всього пару кліків:",
        "nesty_install_1": "Запустіть файл <code>Nestly_Setup.exe</code>.",
        "nesty_install_2": "Дотримуйтесь інструкцій на екрані. Інсталятор автоматично додасть програму в Автозавантаження і пропише контекстне меню.",
        "nesty_install_3": "Готово! Програма вже працює у фоновому режимі.",
        "nesty_dev_title": " Для розробників (Збірка з вихідних кодів)",
        "btn_github": "Подивитися на GitHub",
        "screen_1": "Скрін 1",
        "screen_2": "Скрін 2",
        "screen_3": "Скрін 3",
        "screen_4": "Скрін 4",
        "video": "Відео",
        "btn_repo_closed": "Репозиторій поки закрито",
        "aether_subtitle": "Десктопний AI-асистент для студентів — напівпрозорий overlay поверх усіх вікон із захопленням аудіо та екрану.",
        "aether_feat_title": " Можливості",
        "aether_feat_1": "<strong> Захоплення аудіо:</strong> запис з мікрофона + транскрипція через Whisper (Groq API).",
        "aether_feat_2": "<strong> OCR екрану:</strong> скріншот вибраної області + розпізнавання тексту через Gemini Vision.",
        "aether_feat_3": "<strong> LLM відповіді:</strong> швидка генерація стислих, точних відповідей через Groq LLM.",
        "aether_feat_4": "<strong> Невидимість:</strong> overlay повністю невидимий під час демонстрації екрану (Windows 10/11).",
        "aether_feat_5": "<strong> Гарячі клавіші:</strong> управління без відриву від основного процесу.",
        "aether_install_title": " Встановлення",
        "aether_hotkeys_title": " Гарячі клавіші",
        "aether_hk_col1": "Комбінація",
        "aether_hk_col2": "Дія",
        "aether_hk_1": "Сховати/показати overlay",
        "aether_hk_2": "Увімкнути/вимкнути запис аудіо",
        "aether_hk_3": "Зробити скріншот області",
        "aether_hk_4": "Перемкнути невидимість для демонстрації екрану",
        "aether_hk_5": "Вихід із програми",
        "aether_api_title": " API Ключі",
        "aether_api_desc": "Для роботи необхідні безкоштовні API-ключі:",
        "aether_api_1": "<strong>Groq API</strong> — console.groq.com (STT + LLM, безкоштовно)",
        "aether_api_2": "<strong>Google Gemini API</strong> — aistudio.google.com (OCR, безкоштовно)",
        "aether_api_footer": "Ключі вводяться в налаштуваннях програми (іконка ).",
        "ai_trainer_subtitle": "Потужний інструмент для глибокого та продуктивного вивчення будь-якої інформації з використанням AI.",
        "ai_trainer_concept_title": "Ідея та принцип роботи",
        "ai_trainer_concept_p1": "AI Trainer спочатку розроблявся студентами для студентів з метою спростити глибоке вивчення складної інформації. Однак принцип його роботи робить можливим його використання в будь-якій сфері для абсолютно будь-якої людини незалежно від рівня її знань.",
        "ai_trainer_concept_p2": "В основі складання всіх тестів лежить ШІ, який аналізує заданий Вами матеріал, і на його основі складає певну кількість питань з різними форматами відповідей. Усі виконувані моделі, які доступні Вам у програмі, є частиною безкоштовної некомерційної бібліотеки <code>g4f</code>, що дозволяє використовувати масу закритих моделей без обмежень.",
        "ai_trainer_tech_title": "Технічні деталі",
        "ai_trainer_tech_p1": "За допомогою асинхронної оболонки класу <code>AIClient</code> Ви можете звертатися відразу до декількох моделей одночасно, або ж у різних чатах, при цьому не блокуючи основний потік виконання.",
        "ai_trainer_tech_p2": "<strong>Важлива примітка:</strong> Просимо не підвищувати значення лімітів, таких як <code>ThreadPoolExecutor(max_workers=4)</code> або <code>max_tokens=1200</code>, щоб надмірно не перевантажувати сервери провайдерів.",
        "ai_trainer_lang_title": "Локалізація",
        "androidcalc_subtitle": "Мобільний додаток калькулятора з сучасним дизайном, готовий до інтеграції.",
        "androidcalc_about_title": "Про проєкт",
        "androidcalc_about_p": "Проєкт завершений і повністю готовий до інтеграції. Це повнофункціональний мобільний калькулятор для операційної системи Android із продуманим користувацьким інтерфейсом.",
        "androidcalc_feat_title": "Особливості",
        "androidcalc_feat_1": "Сучасний і чуйний UI/UX дизайн.",
        "androidcalc_feat_2": "Підтримка всіх базових математичних операцій.",
        "androidcalc_feat_3": "Оптимізовано для роботи на пристроях з різною роздільною здатністю екрану.",
        "androidcalc_feat_4": "Чистий і добре задокументований код, готовий до розширення.",
        "deckboard_subtitle": "Потужна екосистема для дистанційного керування вашим комп'ютером прямо зі смартфона.",
        "deckboard_feat_title": " Основні можливості",
        "deckboard_android_title": " Android Додаток (Client)",
        "deckboard_android_1": "<strong>Кастомізація:</strong> Повна свобода дій з підтримкою Drag-and-Drop для сортування плиток.",
        "deckboard_android_2": "<strong>Інтуїтивність:</strong> Сучасний інтерфейс з плавною анімацією та зворотним зв'язком.",
        "deckboard_android_3": "<strong>Розумне підключення:</strong> Автоматичний пошук сервера в локальній мережі або ручне введення IP зі збереженням.",
        "deckboard_pc_title": " PC Сервер (Python)",
        "deckboard_pc_1": "<strong>Керування звуком:</strong> Швидке перемикання мута мікрофона та системного звуку (Speakers).",
        "deckboard_pc_2": "<strong>Інтеграція з OBS:</strong> Дистанційний запуск і зупинка запису через WebSocket.",
        "deckboard_pc_3": "<strong>Запуск софту:</strong> Можливість додавати будь-які ярлики (.exe, .lnk, .url) прямо з системного трея.",
        "deckboard_pc_4": "<strong>Зручність:</strong> Поточна IP-адреса сервера завжди видна в меню трея для швидкого налаштування.",
        "deckboard_structure_title": " Структура проєкту",
        "deckboard_structure_desc": "Репозиторій розділений на дві логічні частини:",
        "deckboard_structure_1": "<code>/AndroidApp</code> — Вихідний код мобільного додатка (Kotlin/Android Studio).",
        "deckboard_structure_2": "<code>/pc-server</code> — Серверна частина на Python з використанням Flask і PyStray.",
        "deckboard_stack_title": " Технологічний стек",
        "deckboard_stack_1": "<strong>Android:</strong> Kotlin, Retrofit2, SharedPreferences, ItemTouchHelper.",
        "deckboard_stack_2": "<strong>Backend:</strong> Python, Flask, OBS-WebSocket, PyCaw, PyStray, NirCmd.",
        "homecinema_badge": " В активній розробці",
        "homecinema_subtitle": "Власний локальний домашній кінотеатр, що зв'язує Android TV з мережевим сховищем.",
        "homecinema_concept_title": "Концепція",
        "homecinema_concept_p1": "HomeCinema — це проєкт, який пов'язує телевізори на базі Android з локальним сховищем (NAS) у домашній мережі, дозволяючи з комфортом дивитися фільми та серіали.",
        "homecinema_concept_p2": "Оформлення та користувацький досвід (UX) натхненні популярними стрімінговими сервісами, але працюють повністю локально і без затримок.",
        "homecinema_feat_title": "Ключові фічі (Поточний білд)",
        "homecinema_feat_1": "<strong>Власна Адмін-панель:</strong> Зручний веб-інтерфейс, через який легко завантажувати нові фільми в бібліотеку.",
        "homecinema_feat_2": "<strong>Розумне автозаповнення:</strong> Під час додавання фільму обкладинки, описи та метадані підтягуються автоматично.",
        "homecinema_feat_3": "<strong>Плавний UI для Android TV:</strong> Інтерфейс адаптований спеціально для керування з пульта дистанційного керування телевізора.",
        "homecinema_note": "Проєкт на даний момент не опубліковано на GitHub, оскільки він перебуває в стадії активної розробки, але вже має повністю робочий білд."
    },
    "en": {
        "nav_home": "Home",
        "nav_spec": "Specialization",
        "nav_process": "Workflow",
        "nav_about": "About",
        "nav_projects": "Projects",
        "nav_status": "Status",
        "hero_badge": "Open to Work",
        "hero_title_1": "Building",
        "hero_title_2": "reliable",
        "hero_title_3": "software solutions",
        "hero_subtitle": "Architecture, development, and automation. From OS utilities to smart mobile apps and AI integrations.",
        "btn_contact_tg": "Message on Telegram",
        "btn_watch_projects": "View Projects",
        "spec_title_1": "My",
        "spec_title_2": "Specialization",
        "spec_subtitle": "Key areas where I bring the most value",
        "spec_desktop": "Desktop Tools",
        "spec_desktop_desc": "Native and cross-platform utilities development (Python/PyQt6, Electron).",
        "spec_mobile": "Mobile Apps",
        "spec_mobile_desc": "Native Android development (Kotlin, Java) and hardware integration.",
        "spec_ai": "AI Integration",
        "spec_ai_desc": "LLM models deployment, data parsing, and smart assistants creation.",
        "spec_auto": "Automation",
        "spec_auto_desc": "Scripts, bots, and web scrapers to automate routine business tasks.",
        "proj_title_1": "My",
        "proj_title_2": "Creations",
        "proj_subtitle": "Selected projects with detailed architecture descriptions",
        "filter_all": "All",
        "filter_desktop": "Desktop",
        "filter_mobile": "Mobile",
        "filter_ai": "AI / LLM",
        "btn_details": "Details",
        "status_dev": "In Development",
        "desc_nesty": "Stylish utility for Windows. Allows creating 'fences' to group desktop shortcuts.",
        "desc_aether": "Desktop AI assistant with audio capture (Groq Whisper) and screen recognition over all windows.",
        "desc_aitrainer": "Tool for deep learning. Analyzes material via AI and generates personalized tests.",
        "desc_deckboard": "PC control ecosystem from smartphone. OBS scene switching, macros, and auto-run.",
        "desc_androidcalc": "Modern calculator app for Android with advanced features.",
        "desc_homecinema": "Custom local media server. Convenient web admin and Android TV client.",
        "workflow_title_1": "My",
        "workflow_title_2": "Workflow",
        "workflow_subtitle": "Transparent and understandable approach to product development",
        "step1_title": "Discussion",
        "step1_desc": "Task analysis, optimal tech stack selection, and tech spec creation.",
        "step2_title": "MVP / Prototype",
        "step2_desc": "Fast creation of a basic version to test hypotheses and mechanics.",
        "step3_title": "Refinement",
        "step3_desc": "Design integration, feature addition, bug fixing, and code optimization.",
        "step4_title": "Support",
        "step4_desc": "Code handover, writing documentation, and deployment consultations.",
        "about_title_1": "About",
        "about_title_2": "Me",
        "about_role": "Vladislav / Developer",
        "about_bio": "I specialize in creating convenient, fast, and aesthetic software solutions. My goal is not just to write code, but to develop tools that truly solve user problems, whether it's desktop customization, AI-assisted learning, or business process automation.",
        "about_placeholder": "Photo placeholder (me.jpg)",
        "about_test1": "\"Slot for a future client review. Great project, done on time!\"",
        "about_test2": "\"Case study or another review that increases trust.\"",
        "status_title_1": "Currently",
        "status_title_2": "Working On",
        "status_subtitle": "Activity log and current project status",
        "time1_date": "2026-06-13",
        "time1_title": "> [DEV] HomeCinema",
        "time1_desc": "Writing web admin for local media server. Metadata autocomplete logic completed.",
        "time2_date": "2026-05-20",
        "time2_title": "> [TEST] Aether",
        "time2_desc": "LLM and OCR integration in desktop assistant. Screen recognition successfully passes QA.",
        "time3_date": "2026-04-15",
        "time3_title": "> [RELEASE] DeckBoard 1.0",
        "time3_desc": "Kotlin + Python stack released. Stable work on Windows and Android.",
        "cta_title": "Ready to discuss a task?",
        "cta_desc": "Tell me about your idea, and we'll find the best technical solution to implement it.",
        "cta_email": "Send Email",
        "footer_rights": " 2026 Владислав. Built with focus on UX.",
        "back_to_portfolio": "← Back to Portfolio",
        "nesty_subtitle_full": "Stylish and lightweight Windows utility created for perfect desktop organization.",
        "label_platform": "Platform:",
        "label_tech": "Technologies:",
        "nesty_feat_title": " Key Features",
        "nesty_feat_1": "<strong> Smart Collapse:</strong> Windows automatically collapse into a thin header when the mouse leaves them, and smoothly expand on hover.",
        "nesty_feat_2": "<strong> Magnetic Snapping:</strong> Fences neatly snap to each other and screen edges (20px distance) for pixel-perfect organization.",
        "nesty_feat_3": "<strong> Deep Customization:</strong> 5 built-in neon presets (Blue, Purple, Green, Orange, Red) + ability to create custom presets via HEX color palette.",
        "nesty_feat_4": "<strong> File Safety:</strong> When deleting a fence, all files inside are automatically and safely moved back to the Desktop.",
        "nesty_feat_5": "<strong> Windows Integration:</strong> Adds 'Create Fence' directly to desktop context menu and auto-starts with system.",
        "nesty_feat_6": "<strong> Drag & Drop:</strong> Easily drag and drop files into the fence with standard mouse movement.",
        "nesty_install_title": " Installation",
        "nesty_install_desc": "Since the program is packed into a full installer, setup takes just a few clicks:",
        "nesty_install_1": "Run the <code>Nestly_Setup.exe</code> file.",
        "nesty_install_2": "Follow the on-screen instructions. The installer will add it to Auto-start and context menu automatically.",
        "nesty_install_3": "Done! The program is already running in the background.",
        "nesty_dev_title": " For Developers (Build from source)",
        "btn_github": "View on GitHub",
        "screen_1": "Screen 1",
        "screen_2": "Screen 2",
        "screen_3": "Screen 3",
        "screen_4": "Screen 4",
        "video": "Video",
        "btn_repo_closed": "Repository is currently closed",
        "aether_subtitle": "Desktop AI assistant for students — a semi-transparent overlay on top of all windows with audio and screen capture.",
        "aether_feat_title": " Features",
        "aether_feat_1": "<strong> Audio capture:</strong> microphone recording + transcription via Whisper (Groq API).",
        "aether_feat_2": "<strong> Screen OCR:</strong> capture selected area + text recognition via Gemini Vision.",
        "aether_feat_3": "<strong> LLM answers:</strong> fast generation of concise, accurate answers via Groq LLM.",
        "aether_feat_4": "<strong> Invisibility:</strong> the overlay is completely invisible during screen sharing (Windows 10/11).",
        "aether_feat_5": "<strong> Hotkeys:</strong> control without distracting from the main process.",
        "aether_install_title": " Installation",
        "aether_hotkeys_title": " Hotkeys",
        "aether_hk_col1": "Combination",
        "aether_hk_col2": "Action",
        "aether_hk_1": "Hide/show overlay",
        "aether_hk_2": "Enable/disable audio recording",
        "aether_hk_3": "Take a screenshot of an area",
        "aether_hk_4": "Toggle invisibility for screen sharing",
        "aether_hk_5": "Exit application",
        "aether_api_title": " API Keys",
        "aether_api_desc": "Free API keys are required to work:",
        "aether_api_1": "<strong>Groq API</strong> — console.groq.com (STT + LLM, free)",
        "aether_api_2": "<strong>Google Gemini API</strong> — aistudio.google.com (OCR, free)",
        "aether_api_footer": "Keys are entered in the application settings ( icon).",
        "ai_trainer_subtitle": "A powerful tool for deep and productive learning of any information using AI.",
        "ai_trainer_concept_title": "Idea and working principle",
        "ai_trainer_concept_p1": "AI Trainer was originally developed by students for students to simplify deep learning of heavy information. However, its working principle makes it possible to use it in any field for absolutely any person regardless of their level of knowledge.",
        "ai_trainer_concept_p2": "At the core of assembling all tests is an AI that analyzes your given material, and based on it compiles a certain number of questions with different answer formats. All executable models available to you in the application are part of the free non-commercial library <code>g4f</code>, which allows you to use a mass of closed models without restrictions.",
        "ai_trainer_tech_title": "Technical details",
        "ai_trainer_tech_p1": "Using the asynchronous wrapper of the <code>AIClient</code> class, you can access multiple models simultaneously, or in different chats, without blocking the main execution thread.",
        "ai_trainer_tech_p2": "<strong>Important note:</strong> Please do not increase limits such as <code>ThreadPoolExecutor(max_workers=4)</code> or <code>max_tokens=1200</code> so as not to overload provider servers excessively.",
        "ai_trainer_lang_title": "Localization",
        "androidcalc_subtitle": "Mobile calculator application with a modern design, ready for integration.",
        "androidcalc_about_title": "About the project",
        "androidcalc_about_p": "The project is completed and fully ready for integration. It is a fully functional mobile calculator for the Android operating system with a well-thought-out user interface.",
        "androidcalc_feat_title": "Features",
        "androidcalc_feat_1": "Modern and responsive UI/UX design.",
        "androidcalc_feat_2": "Support for all basic mathematical operations.",
        "androidcalc_feat_3": "Optimized for devices with different screen resolutions.",
        "androidcalc_feat_4": "Clean and well-documented code, ready for expansion.",
        "deckboard_subtitle": "A powerful ecosystem for remote control of your computer directly from your smartphone.",
        "deckboard_feat_title": " Main features",
        "deckboard_android_title": " Android App (Client)",
        "deckboard_android_1": "<strong>Customization:</strong> Complete freedom of action with Drag-and-Drop support for sorting tiles.",
        "deckboard_android_2": "<strong>Intuitiveness:</strong> Modern interface with smooth animation and feedback.",
        "deckboard_android_3": "<strong>Smart connection:</strong> Automatic server search in the local network or manual IP entry with saving.",
        "deckboard_pc_title": " PC Server (Python)",
        "deckboard_pc_1": "<strong>Audio control:</strong> Quick toggle of microphone mute and system sound (Speakers).",
        "deckboard_pc_2": "<strong>OBS Integration:</strong> Remote start and stop of recording via WebSocket.",
        "deckboard_pc_3": "<strong>Launch software:</strong> Ability to add any shortcuts (.exe, .lnk, .url) right from the system tray.",
        "deckboard_pc_4": "<strong>Convenience:</strong> The current server IP address is always visible in the tray menu for quick setup.",
        "deckboard_structure_title": " Project structure",
        "deckboard_structure_desc": "The repository is divided into two logical parts:",
        "deckboard_structure_1": "<code>/AndroidApp</code> — Source code of the mobile application (Kotlin/Android Studio).",
        "deckboard_structure_2": "<code>/pc-server</code> — Server part on Python using Flask and PyStray.",
        "deckboard_stack_title": " Tech stack",
        "deckboard_stack_1": "<strong>Android:</strong> Kotlin, Retrofit2, SharedPreferences, ItemTouchHelper.",
        "deckboard_stack_2": "<strong>Backend:</strong> Python, Flask, OBS-WebSocket, PyCaw, PyStray, NirCmd.",
        "homecinema_badge": " In active development",
        "homecinema_subtitle": "Your own local home cinema connecting Android TV with network storage.",
        "homecinema_concept_title": "Concept",
        "homecinema_concept_p1": "HomeCinema is a project that connects Android-based TVs with a local network-attached storage (NAS) in your home network, allowing you to comfortably watch movies and series.",
        "homecinema_concept_p2": "The design and user experience (UX) are inspired by popular streaming services, but operate completely locally and without delays.",
        "homecinema_feat_title": "Key features (Current build)",
        "homecinema_feat_1": "<strong>Custom Admin Panel:</strong> A convenient web interface through which it's easy to upload new movies to the library.",
        "homecinema_feat_2": "<strong>Smart autocomplete:</strong> When adding a movie, covers, descriptions, and metadata are pulled automatically.",
        "homecinema_feat_3": "<strong>Smooth UI for Android TV:</strong> The interface is specifically adapted for control from the TV remote.",
        "homecinema_note": "The project is currently not published on GitHub as it is in active development, but already has a fully working build."
    },
    "ru": {
        "nav_home": "Главная",
        "nav_spec": "Специализация",
        "nav_process": "Процесс",
        "nav_about": "Обо мне",
        "nav_projects": "Проекты",
        "nav_status": "Статус",
        "hero_badge": "Открыт для проектов и предложений",
        "hero_title_1": "Создаю",
        "hero_title_2": "надежные",
        "hero_title_3": "программные решения",
        "hero_subtitle": "Архитектура, разработка и автоматизация. От утилит для ОС до умных мобильных приложений и AI-интеграций.",
        "btn_contact_tg": "Написать в Telegram",
        "btn_watch_projects": "Смотреть проекты",
        "spec_title_1": "Моя",
        "spec_title_2": "Специализация",
        "spec_subtitle": "Ключевые направления, в которых я приношу максимальную пользу",
        "spec_desktop": "Desktop Tools",
        "spec_desktop_desc": "Разработка нативных и кроссплатформенных утилит (Python/PyQt6, Electron).",
        "spec_mobile": "Mobile Apps",
        "spec_mobile_desc": "Нативная разработка под Android (Kotlin, Java) и интеграция с железом.",
        "spec_ai": "AI Integration",
        "spec_ai_desc": "Внедрение LLM моделей, парсинг данных и создание умных ассистентов.",
        "spec_auto": "Automation",
        "spec_auto_desc": "Скрипты, боты и веб-парсеры для автоматизации рутинных бизнес-задач.",
        "proj_title_1": "Мои",
        "proj_title_2": "Творения",
        "proj_subtitle": "Избранные проекты с подробным описанием архитектуры",
        "filter_all": "Все",
        "filter_desktop": "Desktop",
        "filter_mobile": "Mobile",
        "filter_ai": "AI / LLM",
        "btn_details": "Подробнее",
        "status_dev": "В разработке",
        "desc_nesty": "Стильная утилита для Windows. Позволяет создавать 'сетки' для группировки ярлыков на рабочем столе.",
        "desc_aether": "Десктопный AI-ассистент с захватом аудио (Groq Whisper) и распознаванием экрана поверх всех окон.",
        "desc_aitrainer": "Инструмент для глубокого обучения. Анализирует материал через AI и генерирует персональные тесты.",
        "desc_deckboard": "Экосистема для управления ПК со смартфона. Переключение сцен OBS, макросы и автозапуск.",
        "desc_androidcalc": "Современное приложение калькулятора для Android с расширенным функционалом.",
        "desc_homecinema": "Собственный локальный медиасервер. Удобная веб-админка и клиент под Android TV.",
        "workflow_title_1": "Процесс",
        "workflow_title_2": "Работы",
        "workflow_subtitle": "Прозрачный и понятный подход к разработке продуктов",
        "step1_title": "Обсуждение",
        "step1_desc": "Анализ задачи, подбор оптимального стека технологий и составление ТЗ.",
        "step2_title": "MVP / Прототип",
        "step2_desc": "Быстрое создание базовой версии для тестирования гипотез и механик.",
        "step3_title": "Доработка",
        "step3_desc": "Интеграция дизайна, добавление фич, отлов багов и оптимизация кода.",
        "step4_title": "Поддержка",
        "step4_desc": "Передача готового кода, написание инструкций и консультации по деплою.",
        "about_title_1": "Обо",
        "about_title_2": "Мне",
        "about_role": "Владислав / Разработчик",
        "about_bio": "Я специализируюсь на создании удобных, быстрых и эстетичных программных решений. Моя цель — не просто писать код, а разрабатывать инструменты, которые действительно решают проблемы пользователей, будь то кастомизация рабочего стола, обучение с помощью AI или автоматизация бизнес-процессов.",
        "about_placeholder": "Заглушка фото (me.jpg)",
        "about_test1": "\"Слот для будущего отзыва заказчика. Отличный проект, сделано в срок!\"",
        "about_test2": "\"Кейс-стади или еще один отзыв, повышающий доверие.\"",
        "status_title_1": "Сейчас в",
        "status_title_2": "Работе",
        "status_subtitle": "Лог активности и актуальный статус проектов",
        "time1_date": "2026-06-13",
        "time1_title": "> [DEV] HomeCinema",
        "time1_desc": "Пишу веб-админку для локального медиасервера. Завершена логика автозаполнения метаданных.",
        "time2_date": "2026-05-20",
        "time2_title": "> [TEST] Aether",
        "time2_desc": "Интеграция LLM и OCR в десктопный ассистент. Распознавание экрана успешно проходит QA.",
        "time3_date": "2026-04-15",
        "time3_title": "> [RELEASE] DeckBoard 1.0",
        "time3_desc": "Связка Kotlin + Python отправлена в релиз. Стабильная работа на Windows и Android.",
        "cta_title": "Готовы обсудить задачу?",
        "cta_desc": "Расскажите о вашей идее, и мы найдем лучшее техническое решение для ее реализации.",
        "cta_email": "Отправить Email",
        "footer_rights": " 2026 Владислав. Создано с фокусом на UX.",
        "back_to_portfolio": "← Назад в Портфолио",
        "nesty_subtitle_full": "Стильная и легковесная утилита для Windows, созданная для идеального порядка на рабочем столе.",
        "label_platform": "Платформа:",
        "label_tech": "Технологии:",
        "nesty_feat_title": " Главные фишки",
        "nesty_feat_1": "<strong> Умное сворачивание:</strong> Окна автоматически сворачиваются в тонкую шапку, когда мышь уходит за их пределы, и плавно разворачиваются при наведении.",
        "nesty_feat_2": "<strong> Магнитное прилипание (Snapping):</strong> Сетки аккуратно магнитятся друг к другу и к краям экрана (дистанция 20 пикселей) для создания идеального пиксельного порядка.",
        "nesty_feat_3": "<strong> Глубокая кастомизация:</strong> 5 встроенных неоновых пресетов (Синий, Фиолетовый, Зеленый, Оранжевый, Красный) + возможность создать свой собственный пресет по HEX-коду через встроенную палитру.",
        "nesty_feat_4": "<strong> Безопасность файлов:</strong> При удалении сетки все файлы из неё автоматически и безопасно перемещаются обратно на Рабочий стол.",
        "nesty_feat_5": "<strong> Интеграция с Windows:</strong> Программа добавляет пункт \"Создать Сетку (Fences)\" прямо в контекстное меню рабочего стола и автоматически запускается вместе с системой.",
        "nesty_feat_6": "<strong> Drag & Drop:</strong> Файлы легко перетаскиваются внутрь сетки обычным движением мыши.",
        "nesty_install_title": " Установка",
        "nesty_install_desc": "Поскольку программа упакована в полноценный инсталлятор, установка занимает всего пару кликов:",
        "nesty_install_1": "Запустите файл <code>Nestly_Setup.exe</code>.",
        "nesty_install_2": "Следуйте инструкциям на экране. Установщик автоматически добавит программу в Автозагрузку и пропишет контекстное меню.",
        "nesty_install_3": "Готово! Программа уже работает в фоновом режиме.",
        "nesty_dev_title": " Для разработчиков (Сборка из исходников)",
        "btn_github": "Посмотреть на GitHub",
        "screen_1": "Скрин 1",
        "screen_2": "Скрин 2",
        "screen_3": "Скрин 3",
        "screen_4": "Скрин 4",
        "video": "Видео",
        "btn_repo_closed": "Репозиторий пока закрыт",

        "aether_subtitle": "Десктопный AI-ассистент для студентов — полупрозрачный overlay поверх всех окон с захватом аудио и экрана.",
        "aether_feat_title": " Возможности",
        "aether_feat_1": "<strong> Захват аудио:</strong> запись с микрофона + транскрипция через Whisper (Groq API).",
        "aether_feat_2": "<strong> OCR экрана:</strong> скриншот выбранной области + распознавание текста через Gemini Vision.",
        "aether_feat_3": "<strong> LLM ответы:</strong> быстрая генерация кратких, точных ответов через Groq LLM.",
        "aether_feat_4": "<strong> Невидимость:</strong> overlay полностью невидим при демонстрации экрана (Windows 10/11).",
        "aether_feat_5": "<strong> Горячие клавиши:</strong> управление без отвлечения от основного процесса.",
        "aether_install_title": " Установка",
        "aether_hotkeys_title": " Горячие клавиши",
        "aether_hk_col1": "Комбинация",
        "aether_hk_col2": "Действие",
        "aether_hk_1": "Скрыть/показать overlay",
        "aether_hk_2": "Включить/выключить запись аудио",
        "aether_hk_3": "Сделать скриншот области",
        "aether_hk_4": "Переключить невидимость для демонстрации экрана",
        "aether_hk_5": "Выход из приложения",
        "aether_api_title": " API Ключи",
        "aether_api_desc": "Для работы необходимы бесплатные API-ключи:",
        "aether_api_1": "<strong>Groq API</strong> — console.groq.com (STT + LLM, бесплатно)",
        "aether_api_2": "<strong>Google Gemini API</strong> — aistudio.google.com (OCR, бесплатно)",
        "aether_api_footer": "Ключи вводятся в настройках приложения (иконка ).",

        "ai_trainer_subtitle": "Мощный инструмент для глубокого и продуктивного обучения любой информации с использованием AI.",
        "ai_trainer_concept_title": "Идея и принцип работы",
        "ai_trainer_concept_p1": "AI Trainer изначально разрабатывался студентами для студентов в целях упростить глубокое обучение тяжёлой информации. Однако принцип его работы делает возможным его использование в любой сфере для абсолютно любого человека в независимости от уровня его знаний.",
        "ai_trainer_concept_p2": "В основе сборки всех тестов лежит ИИ, который анализирует заданный Вами материал, и на его основе составляет определённое количество вопросов с разными форматами ответов. Все исполняемые модели, которые доступны Вам в приложении являются частью бесплатной некоммерческой библиотеки <code>g4f</code>, которая позволяет использовать массу закрытых моделей без ограничений.",
        "ai_trainer_tech_title": "Технические детали",
        "ai_trainer_tech_p1": "С помощью асинхронной оболочки класса <code>AIClient</code> Вы можете обращаться сразу к нескольким моделями одновременно, либо же в разных чатах, при этом не блокируя основной поток выполнения.",
        "ai_trainer_tech_p2": "<strong>Важное примечание:</strong> Просим не повышать значения лимитов, таких как <code>ThreadPoolExecutor(max_workers=4)</code> или <code>max_tokens=1200</code>, чтобы чрезмерно не перегружать сервера провайдеров.",
        "ai_trainer_lang_title": "Локализация",

        "androidcalc_subtitle": "Мобильное приложение калькулятора с современным дизайном, готовое к интегрированию.",
        "androidcalc_about_title": "О проекте",
        "androidcalc_about_p": "Проект завершен и полностью готов к интегрированию. Представляет собой полнофункциональный мобильный калькулятор для операционной системы Android с продуманным пользовательским интерфейсом.",
        "androidcalc_feat_title": "Особенности",
        "androidcalc_feat_1": "Современный и отзывчивый UI/UX дизайн.",
        "androidcalc_feat_2": "Поддержка всех базовых математических операций.",
        "androidcalc_feat_3": "Оптимизировано для работы на устройствах с разным разрешением экрана.",
        "androidcalc_feat_4": "Чистый и хорошо задокументированный код, готовый к расширению.",

        "deckboard_subtitle": "Мощная экосистема для дистанционного управления вашим компьютером прямо со смартфона.",
        "deckboard_feat_title": " Основные возможности",
        "deckboard_android_title": " Android Приложение (Client)",
        "deckboard_android_1": "<strong>Кастомизация:</strong> Полная свобода действий с поддержкой Drag-and-Drop для сортировки плиток.",
        "deckboard_android_2": "<strong>Интуитивность:</strong> Современный интерфейс с плавной анимацией и обратной связью.",
        "deckboard_android_3": "<strong>Умное подключение:</strong> Автоматический поиск сервера в локальной сети или ручной ввод IP с сохранением.",
        "deckboard_pc_title": " PC Сервер (Python)",
        "deckboard_pc_1": "<strong>Управление звуком:</strong> Быстрое переключение мута микрофона и системного звука (Speakers).",
        "deckboard_pc_2": "<strong>Интеграция с OBS:</strong> Дистанционный запуск и остановка записи через WebSocket.",
        "deckboard_pc_3": "<strong>Запуск софта:</strong> Возможность добавлять любые ярлыки (.exe, .lnk, .url) прямо из системного трея.",
        "deckboard_pc_4": "<strong>Удобство:</strong> Текущий IP-адрес сервера всегда виден в меню трея для быстрой настройки.",
        "deckboard_structure_title": " Структура проекта",
        "deckboard_structure_desc": "Репозиторий разделен на две логические части:",
        "deckboard_structure_1": "<code>/AndroidApp</code> — Исходный код мобильного приложения (Kotlin/Android Studio).",
        "deckboard_structure_2": "<code>/pc-server</code> — Серверная часть на Python с использованием Flask и PyStray.",
        "deckboard_stack_title": " Технологический стек",
        "deckboard_stack_1": "<strong>Android:</strong> Kotlin, Retrofit2, SharedPreferences, ItemTouchHelper.",
        "deckboard_stack_2": "<strong>Backend:</strong> Python, Flask, OBS-WebSocket, PyCaw, PyStray, NirCmd.",

        "homecinema_badge": " В активной разработке",
        "homecinema_subtitle": "Собственный локальный домашний кинотеатр, связывающий Android TV с сетевым хранилищем.",
        "homecinema_concept_title": "Концепция",
        "homecinema_concept_p1": "HomeCinema — это проект, который связывает телевизоры на базе Android с локальным хранилищем (NAS) в домашней сети, позволяя с комфортом смотреть фильмы и сериалы.",
        "homecinema_concept_p2": "Оформление и пользовательский опыт (UX) вдохновлены популярными стриминговыми сервисами, но работают полностью локально и без задержек.",
        "homecinema_feat_title": "Ключевые фичи (Текущий билд)",
        "homecinema_feat_1": "<strong>Собственная Админ-панель:</strong> Удобный веб-интерфейс, через который легко загружать новые фильмы в библиотеку.",
        "homecinema_feat_2": "<strong>Умное автозаполнение:</strong> При добавлении фильма обложки, описания и метаданные подтягиваются автоматически.",
        "homecinema_feat_3": "<strong>Плавный UI для Android TV:</strong> Интерфейс адаптирован специально для управления с пульта ДУ телевизора.",
        "homecinema_note": "Проект на данный момент не опубликован на GitHub, так как находится в стадии активной разработки, но уже имеет полностью рабочий билд."
    }
};

document.addEventListener("DOMContentLoaded", () => {
    const langBtns = document.querySelectorAll('.lang-btn');
    const elementsToTranslate = document.querySelectorAll('[data-i18n]');
    
    const setLanguage = (lang) => {
        if (!translations[lang]) return;
        localStorage.setItem('app_lang', lang);
        
        elementsToTranslate.forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[lang][key]) {
                el.innerHTML = translations[lang][key]; 
            }
        });
        
        langBtns.forEach(btn => {
            if (btn.dataset.lang === lang) {
                btn.classList.add('active');
            } else {
                btn.classList.remove('active');
            }
        });
    };

    const savedLang = localStorage.getItem('app_lang') || 'uk';
    setLanguage(savedLang);

    langBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            setLanguage(btn.dataset.lang);
        });
    });

    const themeToggleBtns = document.querySelectorAll('.theme-toggle');
    const moonIcon = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>';
    const sunIcon = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>';

    const savedTheme = localStorage.getItem('app_theme') || 'dark';
    if (savedTheme === 'light') {
        document.body.classList.add('light-theme');
    }

    const updateIcons = () => {
        const isLight = document.body.classList.contains('light-theme');
        themeToggleBtns.forEach(btn => {
            btn.innerHTML = isLight ? moonIcon : sunIcon;
        });
    }
    
    updateIcons();

    themeToggleBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            document.body.classList.toggle('light-theme');
            localStorage.setItem('app_theme', document.body.classList.contains('light-theme') ? 'light' : 'dark');
            updateIcons();
        });
    });
});
